"use client";
import {PublishPackages} from "./publish-packages";
import Link from 'next/link';
import {useState} from 'react';
import {Dialog} from '@/components/ui/dialog';
import {useDraft} from '@/components/draft-provider';
import {createServicePackages,type PackageOption} from '@/app/actions/service-packages';
import {formatMoney,formatPercent} from '@/lib/costs/format';
export function ServicePackages({id,cost,price,scope}:{id:string;cost:number;price:number;scope:string}){
 const [open,setOpen]=useState(false);const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [risk,setRisk]=useState(false);const [created,setCreated]=useState<Array<{id:string;name:string}>>([]);
 const [options,setOptions]=useState<PackageOption[]>(['Ekonomik','Standart','Kapsamlı'].map(name=>({name,cost,price,scope})));
 const draft=useDraft('packages:'+id,{options},s=>{if(Array.isArray(s.options)&&s.options.length===3)setOptions(s.options);});
 const change=(i:number,value:Partial<PackageOption>)=>setOptions(a=>a.map((o,j)=>i===j?{...o,...value}:o));
 return <section className="my-5"><button type="button" onClick={()=>{draft.resume();setOpen(true);}} className="min-h-11 rounded-xl border border-[#e5e5e9] bg-white px-4 text-sm">Üç Hizmet Paketi Hazırla</button>{created.length>0&&<PublishPackages id={created[0].id}/>} {created.length>0&&<div className="mt-3 flex flex-wrap gap-3">{created.map(o=><Link key={o.id} href={`/quotes/${o.id}/edit`} className="min-h-11 py-3 text-sm text-[#0071E3]">{o.name} Taslağını Aç</Link>)}</div>}{open&&<Dialog title="Hizmet paketlerini karşılaştır" className="max-w-4xl" busy={busy} onClose={()=>setOpen(false)}><p className="mb-5 text-sm leading-6 text-[#6E6E73]">Her paket için gerçek maliyeti ve kapsamı gir. Üçü ayrı taslak olarak kaydedilir ve teklif kotasına dahildir. Ardından üç paketi birlikte paylaşıma hazırlayabilirsin; müşteri tek bağlantıda bir paket seçer.</p><form onSubmit={async e=>{e.preventDefault();setBusy(true);setError('');try{const r=await createServicePackages(id,options,risk);if(!r.ok||!r.options){setError(r.error??'Paketler oluşturulamadı.');return;}setCreated(r.options);draft.clear();setOpen(false);}catch{setError('Bağlantı kurulamadı. Taslağın korunuyor.');}finally{setBusy(false);}}}><div className="grid gap-4 md:grid-cols-3">{options.map((o,i)=><div key={i} className="rounded-xl border border-[#e5e5e9] p-4"><label className="block text-sm">Paket adı<input required maxLength={60} value={o.name} onChange={e=>change(i,{name:e.target.value})} className="mt-2 min-h-11 w-full rounded-xl border border-[#e5e5e9] p-3"/></label><label className="mt-3 block text-sm">Kapsam<textarea required maxLength={2000} rows={4} value={o.scope} onChange={e=>change(i,{scope:e.target.value})} className="mt-2 w-full rounded-xl border border-[#e5e5e9] p-3"/></label>{(['cost','price'] as const).map(k=><label key={k} className="mt-3 block text-sm">{k==='cost'?'Maliyet (TL)':'Fiyat (TL)'}<input required type="number" min="0.01" max="1000000000000" step="0.01" value={o[k]} onChange={e=>change(i,{[k]:Number(e.target.value)})} className="mt-2 min-h-11 w-full rounded-xl border border-[#e5e5e9] p-3"/></label>)}<p className={`mt-4 text-sm font-semibold ${o.price<o.cost?'text-red-700':''}`}>Kâr: {formatMoney(o.price-o.cost)} · {formatPercent(o.price>0?(o.price-o.cost)/o.price*100:0)}</p></div>)}</div><label className="mt-5 flex min-h-11 items-start gap-3 text-sm"><input type="checkbox" checked={risk} onChange={e=>setRisk(e.target.checked)} className="mt-1"/>Minimum kârın altındaki veya zarar eden fiyatları kontrol ettim; bu fiyatlarla taslak oluşturmaya devam etmek istiyorum.</label>{error&&<p role="alert" className="mt-3 text-sm text-red-700">{error}</p>}<button disabled={busy} className="mt-4 min-h-12 rounded-xl bg-[#0071E3] px-5 text-sm font-semibold text-white">{busy?'Oluşturuluyor…':'Üç Taslağı Oluştur'}</button></form></Dialog>}</section>;
}
