"use client";
import { useEffect,useState } from "react";
import { listQuoteTemplates,saveQuoteTemplate,type QuoteTemplateContent } from "@/app/actions/quote-templates";
import { Dialog } from "@/components/ui/dialog";
export function TemplateTools({content,onApply}:{content:QuoteTemplateContent;onApply:(content:QuoteTemplateContent)=>void}){
 const [templates,setTemplates]=useState<Awaited<ReturnType<typeof listQuoteTemplates>>>([]);const [name,setName]=useState('');const [selected,setSelected]=useState('');const [open,setOpen]=useState(false);const [confirm,setConfirm]=useState(false);const [message,setMessage]=useState('');const [busy,setBusy]=useState(false);
 async function load(){try{setTemplates(await listQuoteTemplates());}catch{setMessage('Şablonlar yüklenemedi.');}}
 useEffect(()=>{void load();},[]);
 return <section className="mb-5 rounded-2xl border border-[#e5e5e9] bg-white p-5"><h2 className="font-semibold">Teklif şablonları</h2><p className="mt-1 text-xs text-[#6E6E73]">Kapsam ve koşulları tekrar kullan. Müşteri, fiyat ve geçerlilik tarihi şablona kaydedilmez.</p><div className="mt-4 flex flex-wrap gap-2"><select aria-label="Teklif şablonu" value={selected} onChange={e=>setSelected(e.target.value)} className="min-h-11 min-w-0 flex-1 rounded-xl border border-[#e5e5e9] px-3"><option value="">Şablon seç</option>{templates.map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select><button type="button" disabled={!selected} onClick={()=>setConfirm(true)} className="min-h-11 rounded-xl border border-[#e5e5e9] px-4">Uygula</button><button type="button" onClick={()=>{setMessage('');setOpen(true);}} className="min-h-11 rounded-xl border border-[#e5e5e9] px-4">Şablon Olarak Kaydet</button></div>{message&&<p role="status" className="mt-3 text-sm">{message}</p>}{confirm&&<Dialog title="Şablonu uygula" onClose={()=>setConfirm(false)}><p className="text-sm">Başlık, kapsam ve koşullar seçilen şablonla değişecek. Müşteri ve fiyat korunur.</p><button type="button" onClick={()=>{const chosen=templates.find(t=>t.id===selected);if(chosen)onApply(chosen.content);setConfirm(false);}} className="mt-5 min-h-12 w-full rounded-xl bg-[#0071E3] text-white">Alanları Şablonla Değiştir</button></Dialog>}{open&&<Dialog title="Teklif şablonunu kaydet" onClose={()=>setOpen(false)} busy={busy}><form onSubmit={async e=>{e.preventDefault();setBusy(true);try{const r=await saveQuoteTemplate(name,content);setMessage(r.ok?'Şablon kaydedildi.':r.error||'Şablon kaydedilemedi.');if(r.ok){setOpen(false);setName('');await load();}}catch{setMessage('Bağlantı kurulamadı.');}finally{setBusy(false);}}}><label className="block text-sm font-medium">Şablon adı<input required maxLength={100} value={name} onChange={e=>setName(e.target.value)} className="mt-3 min-h-12 w-full rounded-xl border border-[#e5e5e9] px-3"/></label><p className="mt-3 text-xs text-[#6E6E73]">Aynı isimli bir şablon varsa güncellenir.</p>{message&&<p role="status" className="mt-3 text-sm">{message}</p>}<button disabled={busy} className="mt-5 min-h-12 w-full rounded-xl bg-[#0071E3] text-white">{busy?'Kaydediliyor…':'Kaydet'}</button></form></Dialog>}</section>;
}
