"use client";
import Link from "next/link";
import { useState } from "react";
import { Check, Sparkles } from "lucide-react";
import type { Plan, PlanId } from "@/types/database";

const featureLabels = [
  ["public_quotes", "Paylaşılabilir teklif bağlantısı"], ["pdf", "PDF teklif"],
  ["whatsapp", "WhatsApp ile paylaşım"], ["actual_profit", "Gerçek kâr takibi"],
  ["advanced_reports", "Gelişmiş raporlar"], ["remove_branding", "KaçaYapayım ibaresini kaldırma"],
  ["business_logo", "Teklifte işletme logosu"],
] as const;

export function PlanCards({ plans, currentPlan, marketing = false }: { plans: Plan[]; currentPlan?: PlanId; marketing?: boolean }) {
  const [interval, setInterval] = useState<"monthly" | "yearly">("monthly");
  return <div className={marketing ? "marketing-plans" : undefined}><div className="mb-6 inline-flex rounded-[14px] bg-[#eaeaee] p-1" role="group" aria-label="Ödeme dönemi"><button type="button" aria-pressed={interval === "monthly"} onClick={() => setInterval("monthly")} className={`min-h-10 rounded-[11px] px-5 text-[13px] font-semibold ${interval === "monthly" ? "bg-white shadow-sm" : "text-[#6E6E73]"}`}>Aylık</button><button type="button" aria-pressed={interval === "yearly"} onClick={() => setInterval("yearly")} className={`min-h-10 rounded-[11px] px-5 text-[13px] font-semibold ${interval === "yearly" ? "bg-white shadow-sm" : "text-[#6E6E73]"}`}>Yıllık</button></div>
  <div className="grid gap-4 lg:grid-cols-3">{plans.map((plan) => { const paid = plan.id !== "free"; const price = interval === "monthly" ? plan.monthly_price_kurus : plan.yearly_price_kurus; return <section key={plan.id} className={`relative flex flex-col rounded-[22px] border bg-white p-6 shadow-[0_8px_30px_rgba(29,29,31,.035)] sm:p-7 ${plan.id === "usta" ? "border-[#0071E3]" : "border-[#e5e5e9]"}`}>{plan.id === "usta" && <span className="absolute -top-3 left-6 inline-flex items-center gap-1 rounded-full bg-[#0071E3] px-3 py-1 text-[11px] font-semibold text-white"><Sparkles size={12} />{marketing ? "Düzenli işler için" : "Önerilen"}</span>}<h3 className="text-[23px] font-semibold tracking-tight">{plan.name}</h3><p className="mt-2 min-h-10 text-[13px] leading-5 text-[#6E6E73]">{plan.description}</p><div className="mt-5"><span className="text-[34px] font-semibold tracking-[-0.05em]">{new Intl.NumberFormat("tr-TR").format(price / 100)} ₺</span><span className="ml-1 text-[13px] text-[#6E6E73]">/{interval === "monthly" ? "ay" : "yıl"}</span></div>{paid && interval === "yearly" && <p className="mt-1 text-[12px] text-[#6E6E73]">Aylık karşılığı {new Intl.NumberFormat("tr-TR", { maximumFractionDigits: 2 }).format(price / 1200)} ₺</p>}<div className="mt-6 border-t border-[#eeeef1] pt-5"><p className="text-[13px] font-semibold">{plan.limits.monthly_quotes === null ? "Sınırsız teklif" : `Ayda ${plan.limits.monthly_quotes} teklif`}</p><p className="mt-1 text-[13px] text-[#6E6E73]">{plan.limits.active_customers === null ? "Sınırsız müşteri" : `${plan.limits.active_customers} aktif müşteri`}</p></div><ul className="mt-5 flex-1 space-y-3">{featureLabels.filter(([key]) => plan.features[key]).map(([key, label]) => <li key={key} className="flex items-start gap-2 text-[13px] leading-5"><Check size={16} className="mt-0.5 shrink-0 text-[#23804d]" />{label}</li>)}</ul><div className="mt-7">{currentPlan === plan.id ? <span className="flex min-h-11 items-center justify-center rounded-[12px] bg-[#f0f0f3] px-4 text-[13px] font-semibold">Mevcut paketin</span> : marketing && !paid ? <Link href="/register" className="marketing-primary w-full">Ücretsiz Başla</Link> : <span className="flex min-h-11 items-center justify-center rounded-[12px] bg-[#f0f0f3] px-4 text-center text-[13px] font-medium text-[#6E6E73]">{paid ? "Ödeme bağlantısı hazırlanıyor" : "Ücretsiz başla"}</span>}</div></section>; })}</div><p className="mt-4 text-[12px] leading-5 text-[#86868b]">Fiyatlar TL cinsindendir. Vergi ve ödeme koşulları, ödeme sağlayıcısı bağlandığında ödeme ekranında gösterilecektir.</p></div>;
}

