import { WorkPanel } from "@/components/work/work-panel";
import { RecordTools } from "@/components/work/record-tools";
import Link from "next/link";
import { notFound } from "next/navigation";
import { ArrowLeft, Pencil } from "lucide-react";
import { ButtonLink, Card } from "@/components/ui";
import { JobCostSummary } from "@/components/jobs/job-cost-summary";
import { JobSavedToast } from "@/components/jobs/job-saved-toast";
import { getJobBundle } from "@/lib/jobs/service";
import { formatQuantity } from "@/lib/jobs/format";
import { formatCustomerDate } from "@/lib/customers/format";
import { formatMoney, formatPercent } from "@/lib/costs/format";
import { getQuotesForJob } from "@/lib/quotes/service";
import { QuoteStatusBadge } from "@/lib/quotes/format";
import { JobLifecycleActions } from "@/components/jobs/job-lifecycle-actions";
import { GenericJobDetail } from "@/components/jobs/generic-job-detail";
import { actualProfitSummary, canStartJob, jobStatusLabel } from "@/lib/jobs/lifecycle";
import type { PainterCalculation } from "@/lib/jobs/painter-calculation";

export const metadata = { title: "İş Detayı" };
export default async function JobDetailPage({ params, searchParams }: { params: Promise<{ id: string }>; searchParams: Promise<{ saved?: string; priced?: string }> }) {
  const { id } = await params;
  const flags = await searchParams;
  const [bundle, jobQuotes] = await Promise.all([getJobBundle(id), getQuotesForJob(id)]);
  if (!bundle) notFound();
  if (!bundle.details) return <GenericJobDetail job={bundle.job} customer={bundle.customer} breakdown={bundle.breakdown}
    quotes={jobQuotes} acceptedQuote={bundle.acceptedQuote} />;
  const { job, details, breakdown, customer, acceptedQuote } = bundle;
  const actualSummary = acceptedQuote && job.actual_cost !== null
    ? actualProfitSummary(acceptedQuote.sale_price, acceptedQuote.estimated_cost_snapshot, job.actual_cost) : null;
  const sum = (type: "material" | "labor" | "fixed" | "extra") => breakdown.filter((line) => line.source_type === type)
    .reduce((total, line) => total + Math.round(line.total_cost * 100), 0) / 100;
  const calculation: PainterCalculation = { breakdown: breakdown.map((line) => ({
    cost_item_id: line.cost_item_id || "", name: line.name, category: line.category, unit: line.unit,
    quantity: line.quantity, unit_cost: line.unit_cost, total_cost: line.total_cost,
    source_type: line.source_type, metadata: line.metadata as Record<string, number>,
  })), material_total: sum("material"), labor_total: sum("labor"), other_total: sum("fixed") + sum("extra"),
    grand_total: job.estimated_cost, warnings: [] };
  return <div className="mx-auto max-w-[900px]"><div className="mb-5 flex items-center justify-between gap-3"><Link href="/jobs" className="inline-flex min-h-11 items-center gap-2 text-[14px] font-medium text-[#6E6E73]"><ArrowLeft size={17} />İşlerim</Link>{["draft", "calculated"].includes(job.status) && <ButtonLink href={`/new-quote?job_id=${job.id}`} variant="secondary"><Pencil size={16} />İşi Düzenle</ButtonLink>}</div>
    {flags.saved === "1" && <JobSavedToast id={id} />}
    <RecordTools id={id} type="job" /><WorkPanel jobId={id} />
    <h1 className="text-[32px] font-semibold leading-tight tracking-[-0.05em] sm:text-[40px]">{job.title}</h1><p className="mt-2 text-[14px] text-[#6E6E73]">{formatCustomerDate(job.created_at)} · {jobStatusLabel[job.status]}</p>
    {acceptedQuote && <Card className="mt-6 p-5 sm:p-6"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-xs font-semibold uppercase tracking-wide text-[#6E6E73]">{job.status === "completed" ? "İş tamamlandı" : job.status === "in_progress" ? "Devam eden iş" : "✓ Teklif kabul edildi"}</p><h2 className="mt-2 text-2xl font-semibold">{formatMoney(acceptedQuote.sale_price)}</h2><p className="mt-1 text-sm text-[#6E6E73]">{customer?.name || "Müşteri"} · {acceptedQuote.quote_number}</p>{acceptedQuote.accepted_at && <p className="mt-1 text-xs text-[#6E6E73]">Kabul: {new Date(acceptedQuote.accepted_at).toLocaleString("tr-TR", { timeZone: "Europe/Istanbul", dateStyle: "medium", timeStyle: "short" })}</p>}{job.started_at && <p className="mt-1 text-xs text-[#6E6E73]">Başlangıç: {new Date(job.started_at).toLocaleString("tr-TR", { timeZone: "Europe/Istanbul", dateStyle: "medium", timeStyle: "short" })}</p>}</div>{canStartJob(job.status) ? <JobLifecycleActions id={id} /> : job.status === "in_progress" ? <ButtonLink href={`/jobs/${id}/complete`}>İşi Tamamla</ButtonLink> : job.status === "completed" ? <ButtonLink href={`/jobs/${id}/complete`} variant="secondary">Gerçek Maliyeti Düzenle</ButtonLink> : null}</div></Card>}
    {job.status === "completed" && actualSummary && <Card className="mt-5 p-5 sm:p-7"><p className="text-xs font-semibold uppercase tracking-wide text-[#6E6E73]">İş tamamlandı{job.completed_at ? ` · ${new Date(job.completed_at).toLocaleString("tr-TR", { timeZone: "Europe/Istanbul", dateStyle: "medium", timeStyle: "short" })}` : ""}</p><p className="mt-3 text-[clamp(2rem,6vw,3rem)] font-semibold tracking-[-0.055em]">{formatMoney(actualSummary.actualProfit)}</p><p className="text-sm text-[#6E6E73]">{actualSummary.actualProfit < 0 ? "Gerçek zarar" : "Gerçek kâr"} · {formatPercent(actualSummary.actualMargin)} marj</p><div className="mt-5 grid grid-cols-2 gap-4 border-t border-[#ececf0] pt-5 text-sm"><div><p className="text-[#6E6E73]">Teklif</p><p className="mt-1 font-semibold">{formatMoney(acceptedQuote!.sale_price)}</p></div><div><p className="text-[#6E6E73]">Gerçek maliyet</p><p className="mt-1 font-semibold">{formatMoney(actualSummary.actualCost)}</p></div><div><p className="text-[#6E6E73]">Tahmini maliyet</p><p className="mt-1 font-semibold">{formatMoney(acceptedQuote!.estimated_cost_snapshot)}</p></div><div><p className="text-[#6E6E73]">Tahmini kâr</p><p className="mt-1 font-semibold">{formatMoney(acceptedQuote!.estimated_profit_snapshot)}</p></div></div><p className="mt-5 border-t border-[#ececf0] pt-4 text-sm text-[#6E6E73]">{actualSummary.profitVariance < 0 ? `Tahmininden ${formatMoney(-actualSummary.profitVariance)} daha az kâr ettin.` : actualSummary.profitVariance > 0 ? `Tahmininden ${formatMoney(actualSummary.profitVariance)} daha fazla kâr ettin.` : "Kârın tahmininle aynı."}</p>{job.completion_notes && <p className="mt-3 whitespace-pre-wrap text-sm">{job.completion_notes}</p>}</Card>}
    {!acceptedQuote && jobQuotes[0]?.status === "rejected" && <Card className="mt-5 p-5"><p className="text-sm font-medium">Son teklif reddedildi.</p><ButtonLink href={`/quotes/new?job_id=${id}`} variant="secondary" className="mt-3">Yeni Teklif Oluştur</ButtonLink></Card>}
    <Card className="mt-7 p-5 sm:p-6"><h2 className="text-[18px] font-semibold">İş Bilgileri</h2><div className="mt-5 grid gap-4 text-[14px] sm:grid-cols-2"><div><p className="text-[12px] text-[#6E6E73]">Müşteri</p><p className="mt-1 font-medium">{customer ? <Link href={`/customers/${customer.id}`} className="text-[#0071E3] hover:underline">{customer.name}</Link> : "Müşterisiz iş"}</p></div><div><p className="text-[12px] text-[#6E6E73]">Boyanacak alan</p><p className="mt-1 font-medium">{formatQuantity(details.wall_area)} m² duvar{details.ceiling_area > 0 ? ` · ${formatQuantity(details.ceiling_area)} m² tavan` : ""}</p></div><div><p className="text-[12px] text-[#6E6E73]">Uygulama</p><p className="mt-1 font-medium">{details.wall_coats} kat boya{details.primer_required ? ` · ${details.primer_coats} kat astar` : ""}{details.putty_required ? " · Macun" : ""}</p></div><div><p className="text-[12px] text-[#6E6E73]">İşçilik</p><p className="mt-1 font-medium">{formatQuantity(details.days)} gün · {details.master_count} usta + {details.helper_count} yardımcı</p></div></div>{job.description && <p className="mt-5 border-t border-[#ececf0] pt-4 text-[14px] text-[#515159]">{job.description}</p>}{details.notes && <p className="mt-3 whitespace-pre-wrap text-[14px] text-[#515159]">{details.notes}</p>}</Card>
    <div className="mt-5"><JobCostSummary calculation={calculation} /></div><p className="mt-4 text-[12px] leading-5 text-[#6E6E73]">Bu maliyetler {job.calculated_at ? formatCustomerDate(job.calculated_at) : "hesaplama anında"} tarihinde kaydedilen fiyatlara dayanır. Maliyetlerim sayfasındaki değişiklikler bu işi otomatik güncellemez.</p>
    <Card className="mt-6 p-5 sm:p-6"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-[12px] font-semibold uppercase tracking-[0.1em] text-[#6E6E73]">Satış fiyatı</p><h2 className="mt-2 text-[24px] font-semibold tracking-[-0.04em]">{acceptedQuote ? formatMoney(acceptedQuote.sale_price) : job.selected_sale_price !== null ? formatMoney(job.selected_sale_price) : "Henüz belirlenmedi"}</h2></div>{["draft", "calculated"].includes(job.status) && <ButtonLink href={`/new-quote?job_id=${job.id}&step=pricing`}>{job.selected_sale_price !== null ? "Fiyatı Düzenle" : "Fiyatını Belirle"}</ButtonLink>}</div>{job.selected_sale_price !== null && <div className="mt-5 grid gap-4 border-t border-[#ececf0] pt-5 text-[14px] sm:grid-cols-3"><div><p className="text-[#6E6E73]">Tahmini kâr</p><p className="mt-1 font-semibold">{formatMoney(acceptedQuote ? acceptedQuote.estimated_profit_snapshot : job.estimated_profit ?? 0)}</p></div><div><p className="text-[#6E6E73]">Kâr marjı</p><p className="mt-1 font-semibold">{formatPercent(acceptedQuote ? acceptedQuote.profit_margin_snapshot : job.estimated_profit_margin)}</p></div><div><p className="text-[#6E6E73]">Önerilen fiyat</p><p className="mt-1 font-semibold">{job.recommended_sale_price === null ? "—" : formatMoney(job.recommended_sale_price)}</p></div></div>}{job.pricing_cost_changed && <p className="mt-5 rounded-xl bg-[#f4f9ff] px-4 py-3 text-[13px] text-[#315d85]">Maliyet değişti. Teklif marjını yeniden kontrol et.</p>}</Card>
    <Card className="mt-6 p-5 sm:p-6"><div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="text-[18px] font-semibold">Teklifler</h2><p className="mt-1 text-[13px] text-[#6E6E73]">Bu iş için hazırladığın müşteri teklifleri.</p></div>{["draft", "calculated", "quoted"].includes(job.status) && job.selected_sale_price !== null && <ButtonLink href={`/quotes/new?job_id=${job.id}`} variant="secondary">Teklif Oluştur</ButtonLink>}</div>{jobQuotes.length ? <div className="mt-5 divide-y divide-[#ececf0] border-t border-[#ececf0]">{jobQuotes.map((quote) => <Link href={`/quotes/${quote.id}`} key={quote.id} className="flex min-h-16 items-center justify-between gap-3 py-3 hover:text-[#0071E3]"><div><p className="text-[14px] font-semibold">{quote.quote_number}</p><p className="mt-1 text-[13px] text-[#6E6E73]">{formatMoney(quote.sale_price)}</p></div><QuoteStatusBadge quote={quote} /></Link>)}</div> : <p className="mt-5 text-[13px] text-[#6E6E73]">Henüz teklif hazırlanmadı.</p>}</Card>
  </div>;
}
