export const professions = [
  { slug: "boyaci", name: "Boyacı", symbol: "◒", short: "Boya, astar, sarf ve işçilik maliyetlerini bir arada hesapla.", title: "Boyacı Teklif ve Maliyet Hesaplama Programı", heading: "Boyama işlerini doğru fiyatlandır.", intro: "Bir boyama işinde metrekare tek başına fiyat değildir. Kat sayısı, boya örtücülüğü, astar, tavan, macun, fire, işçilik ve yol gideri toplam maliyeti değiştirir.", steps: ["Duvar ve tavan alanını, uygulanacak kat sayısını ayrı yaz.", "Boya ve astar miktarını örtücülük ile fire payına göre hesapla.", "Usta ve yardımcıların gün sayısını; sarf ile yolu ekle.", "Toplam maliyete hedef satış marjını uygula ve kapsamı açık bir teklife dök."], example: "Örneğin maliyet 57.510 TL ve hedef marj %30 ise hesap 57.510 ÷ 0,70 = 82.157,14 TL olur. Yüz TL yukarı yuvarlandığında öneri 82.200 TL'dir.", calculator: "/hesaplama-araclari/boya-maliyeti", guide: "/rehber/boyaci-teklifi-nasil-hazirlanir" },
  { slug: "elektrikci", name: "Elektrikçi", symbol: "ϟ", short: "Kablo, priz, sigorta ve iş gününü teklif hesabına kat.", title: "Elektrikçi İş Maliyeti ve Teklif Hesaplama", heading: "Elektrik işinde her kalemi görünür kıl.", intro: "Elektrik işlerinde adet ve uzunluk kadar montaj süresi de belirleyicidir. Priz ve anahtar sayısı, farklı kesitte kablo, sigorta, buat, yardımcı işçilik ve sarf malzemesi ayrı izlenmelidir.", steps: ["Kablo metrajını kesite göre ayır ve fire payı ekle.", "Priz, anahtar, sigorta ve buat adetlerini birim maliyetleriyle çarp.", "Elektrikçi ve yardımcı için iş günü maliyetini hesapla.", "Yol ve sarfı ekledikten sonra hedef marjla fiyatı belirle."], example: "Örneğin malzeme 12.000 TL, işçilik 8.000 TL, yol ve sarf 1.000 TL ise maliyet 21.000 TL'dir. %30 hedef marj için fiyat 21.000 ÷ 0,70 = 30.000 TL olur.", calculator: "/hesaplama-araclari/elektrik-isi-maliyeti", guide: "/rehber/elektrik-isi-nasil-fiyatlandirilir" },
  { slug: "tesisatci", name: "Tesisatçı", symbol: "≈", short: "Boru, bağlantı, montaj ve yol giderini unutma.", title: "Tesisatçı Maliyet ve Teklif Hesaplama", heading: "Tesisat işinin gerçek kapsamını fiyatına yansıt.", intro: "Boru uzunluğu, bağlantı parçaları, armatürler ve montaj süresi farklı işlerde farklı ağırlık taşır. Kırma ve onarım gibi kapsam dışı işleri teklif öncesi netleştirmek de önemlidir.", steps: ["Malzeme miktarlarını ve birim alış maliyetlerini belirle.", "Montaj günü, yardımcı işçilik ve yol maliyetini ekle.", "Beklenebilecek sarf ve fireyi ayrıca değerlendir.", "Kapsamı ve hariç tutulan işleri teklifte açıkça yaz."], example: "Malzeme 8.000 TL, işçilik 6.000 TL, yol ve sarf 1.000 TL ise 15.000 TL maliyet oluşur. %25 marj için 15.000 ÷ 0,75 = 20.000 TL satış fiyatı gerekir.", calculator: "/hesaplama-araclari/kar-marji", guide: "/rehber/is-maliyeti-nasil-hesaplanir" },
  { slug: "klimaci", name: "Klimacı", symbol: "✳", short: "Montaj malzemesi, işçilik ve servis yolunu birlikte gör.", title: "Klimacı İş Maliyeti ve Teklif Programı", heading: "Montaj ve servis işlerini güvenle fiyatlandır.", intro: "Klima montajında bakır boru, izolasyon, drenaj, konsol ve bağlantı malzemeleriyle işçilik ve ulaşım birlikte hesaplanmalıdır. Cihazın dahil olup olmadığı teklif kapsamında açık olmalıdır.", steps: ["Montaj metrajını ve kullanılacak parçaları kaydet.", "İşçilik süresini ve gerekiyorsa ikinci personeli ekle.", "Yol, sarf ve olası ek işler için kapsamı belirle.", "Hedef marja göre fiyatı hesaplayıp müşteriye paylaş."], example: "Malzeme 5.000 TL, işçilik 4.000 TL ve ulaşım 1.000 TL ise 10.000 TL maliyet oluşur. %20 marj için 10.000 ÷ 0,80 = 12.500 TL gerekir.", calculator: "/hesaplama-araclari/kar-marji", guide: "/rehber/teklif-fiyati-nasil-belirlenir" },
] as const;

export const guides = [
  { slug: "kar-marji-nasil-hesaplanir", title: "Kâr marjı nasıl hesaplanır?", answer: "Kâr marjı, satış fiyatından maliyet çıkarıldıktan sonra kalan kârın satış fiyatına oranıdır.", formula: "Kâr = Satış fiyatı − maliyet. Kâr marjı = kâr ÷ satış fiyatı × 100.", example: "20.000 TL maliyetli iş 28.600 TL'ye satılırsa kâr 8.600 TL, gerçekleşen marj yaklaşık %30,07 olur. Tam %30 marj için 20.000 ÷ 0,70 = 28.571,43 TL gerekir; uygulama bunu yüz TL yukarı yuvarlar.", detail: "Maliyete %30 eklemek 26.000 TL verir; bu fiyatın marjı %23,08'dir. Markup ile marjı karıştırmak teklifin beklenenden az kazandırmasına yol açar.", related: "/hesaplama-araclari/kar-marji" },
  { slug: "is-maliyeti-nasil-hesaplanir", title: "İş maliyeti nasıl hesaplanır?", answer: "İş maliyeti, işi tamamlamak için beklenen malzeme, işçilik, sarf, ulaşım ve diğer doğrudan giderlerin toplamıdır.", formula: "Toplam maliyet = malzeme + işçilik + sarf + yol + diğer doğrudan giderler.", example: "12.000 TL malzeme, 8.000 TL işçilik, 800 TL sarf ve 700 TL yol gideri olan işin tahmini maliyeti 21.500 TL'dir.", detail: "Tekliften önce miktarı ve birim maliyeti ayrı kaydet. İş bittikten sonra gerçekleşen giderleri karşılaştır; farkın nedenini sonraki işlerde kullan.", related: "/hesaplama-araclari/teklif-fiyati" },
  { slug: "teklif-fiyati-nasil-belirlenir", title: "Teklif fiyatı nasıl belirlenir?", answer: "Önce kendi toplam maliyetini bul, ardından hedeflediğin satış kâr marjına göre gereken fiyatı hesapla.", formula: "Hedef fiyat = toplam maliyet ÷ (1 − hedef marj / 100).", example: "30.000 TL maliyet ve %25 hedef marj için fiyat 30.000 ÷ 0,75 = 40.000 TL'dir. Bu fiyatın 10.000 TL'si brüt kârdır.", detail: "Fiyata geçmeden kapsamı, hariç işleri, ödeme planını ve teklif geçerlilik süresini netleştir. KaçaYapayım piyasa rayici üretmez; senin girdiğin maliyet ve hedef marjla çalışır.", related: "/hesaplama-araclari/teklif-fiyati" },
  { slug: "markup-ve-marj-farki", title: "Markup ve marj arasındaki fark nedir?", answer: "Markup kârı maliyete, marj ise satış fiyatına böler. Aynı yüzde kullanıldığında farklı satış fiyatları çıkar.", formula: "Markup = kâr ÷ maliyet × 100. Marj = kâr ÷ satış fiyatı × 100.", example: "20.000 TL maliyete %30 markup: 26.000 TL fiyat ve %23,08 marj. %30 marj hedefi: yaklaşık 28.571,43 TL fiyat ve %42,86 markup.", detail: "Müşteriye verilecek fiyatı hedef satış marjından üretmek istiyorsan maliyeti 1 + oranla çarpmak yerine 1 − oranına böl.", related: "/hesaplama-araclari/kar-marji" },
  { slug: "iscilik-maliyeti-nasil-hesaplanir", title: "İşçilik maliyeti nasıl hesaplanır?", answer: "İşçilik maliyeti, işi yapacak kişilerin süre ve birim çalışma maliyetlerinin toplamıdır.", formula: "İşçilik = Σ (kişi sayısı × iş günü × kişi başı günlük maliyet).", example: "Bir usta 3 gün boyunca günlük 3.000 TL, bir yardımcı 2 gün boyunca günlük 1.800 TL çalışırsa işçilik 9.000 + 3.600 = 12.600 TL olur.", detail: "Yarım gün, fazla mesai ve tekrar ziyaret ihtimalini işin gerçek planına göre değerlendir. Buradaki rakamlar yalnızca hesap örneğidir; ücret tarifesi değildir.", related: "/hesaplama-araclari/teklif-fiyati" },
  { slug: "boyaci-teklifi-nasil-hazirlanir", title: "Boyacı teklifi hazırlarken neleri hesaplamalı?", answer: "Boya teklifinde alan, kat sayısı, örtücülük, fire, hazırlık, astar, tavan, işçilik ve yol birlikte düşünülmelidir.", formula: "Boya miktarı = alan × kat sayısı ÷ litre başına örtücülük × (1 + fire oranı).", example: "100 m² duvar, 2 kat, 10 m²/L örtücülük ve %10 fire varsayımıyla yaklaşık 22 L duvar boyası gerekir. Birim boya maliyeti ayrıca girilmelidir.", detail: "Macun ve yüzey onarımı her işte aynı değildir. Uygulanacak alanı ayrı belirt; teklif kapsamına dahil olmayan büyük tamiratları açıkça yaz.", related: "/hesaplama-araclari/boya-maliyeti" },
  { slug: "elektrik-isi-nasil-fiyatlandirilir", title: "Elektrik işi fiyatlandırması nasıl yapılır?", answer: "Elektrik işinin fiyatı, malzeme adet ve metrajı ile işçilik süresi ve diğer giderlerin toplamından hareketle belirlenir.", formula: "Maliyet = kablo + priz + anahtar + sigorta + buat + işçilik + sarf + yol.", example: "100 m kablo × 20 TL, 10 priz × 250 TL ve 2 gün × 3.000 TL işçilik için bu üç kalemin maliyeti 10.500 TL'dir. Diğer kalemler ayrıca eklenir.", detail: "Kablo kesiti ve ürün markası maliyeti değiştirebilir. Keşifte belirlenmeyen işleri kapsam dışı olarak tanımlayıp sonradan ayrıca fiyatlandır.", related: "/hesaplama-araclari/elektrik-isi-maliyeti" },
  { slug: "teklifte-odeme-kosullari", title: "Teklifte ödeme koşulları nasıl yazılır?", answer: "Ödeme koşullarında tutarı, vadeyi, olası avansı ve kalan ödemenin hangi iş aşamasında yapılacağını açıkça belirt.", formula: "Ödenecek toplam = avans + ara ödeme + teslim ödemesi.", example: "40.000 TL'lik örnek işte %30 avans 12.000 TL, teslimde kalan ödeme 28.000 TL olarak yazılabilir. Bu yalnızca örnek bir plan; tarafların anlaştığı koşullar esas alınır.", detail: "Belirsiz 'iş sonunda ödeme' ifadesi yerine tarih veya tamamlanma ölçütü koy. Vergi ve hukuki yükümlülüklerin için güncel uzman görüşü al.", related: "/hesaplama-araclari/teklif-fiyati" },
  { slug: "pazarlikta-ne-kadar-indirim", title: "Müşteri pazarlığında ne kadar indirim yapılabilir?", answer: "İndirimi, işin hesaplanan maliyeti ve kabul edebileceğin en düşük kâr marjı üzerinden sınırla.", formula: "Minimum fiyat = maliyet ÷ (1 − minimum marj / 100). İndirim alanı = teklif fiyatı − minimum fiyat.", example: "20.000 TL maliyet, %30 hedef ve %20 alt sınırda hedef fiyat yaklaşık 28.571 TL; minimum fiyat 25.000 TL'dir. Bu iki fiyat arasındaki fark yaklaşık 3.571 TL'dir.", detail: "İndirim vermeden önce kapsamı azaltma veya ödeme koşulunu değiştirme seçeneklerini konuş. Alt sınırın altına inmek bilinçli bir iş kararı olmalı.", related: "/hesaplama-araclari/kar-marji" },
] as const;

export const contentUpdatedAt = "2026-09-30";

export const guideChecks: Record<string, { heading: string; items: string[]; caution: string }> = {
  "kar-marji-nasil-hesaplanir": { heading: "Tekliften önce üç kontrol", items: ["Toplam maliyete yol, sarf ve işçilik dahil mi? Eksik gider marjı kâğıt üzerinde yükseltir.", "Hedef yüzdeyi satış fiyatına göre mi belirledin? Maliyete eklenen aynı yüzde farklı sonuç verir.", "Yuvarlanmış satış fiyatıyla gerçekleşen marjı tekrar hesapla; yuvarlama hedefi aşağı çekmemeli."], caution: "Marj brüt iş sonucunu gösterir. İşletmenin genel giderleri, vergiler ve tahsilat riski ayrıca değerlendirilmelidir." },
  "is-maliyeti-nasil-hesaplanir": { heading: "Maliyeti oluştururken", items: ["Malzemeyi miktar × birim maliyet olarak yaz; tek toplu sayı sonradan kontrolü zorlaştırır.", "İşçiliği çalışan sayısı ve gün sayısına ayır; keşif, hazırlık ve ikinci ziyaretleri hesaba kat.", "Yol, sarf ve öngörülebilir fireyi ayrı satırda tut; tekliften sonra gerçek giderle karşılaştır."], caution: "Örnekteki 21.500 TL maliyet bir piyasa ortalaması değildir. Her işletme kendi alış fiyatını ve çalışma maliyetini girmelidir." },
  "teklif-fiyati-nasil-belirlenir": { heading: "Fiyatı müşteriye göndermeden", items: ["İşin dahil ve hariç kapsamını müşteriyle aynı şekilde anladığından emin ol.", "Toplam maliyet ve hedef marjla öneriyi üret; varsa minimum kabul marjını ayrıca hesapla.", "Teklifin geçerlilik süresi, ödeme koşulu ve değişikliklerin nasıl fiyatlanacağını yaz."], caution: "Öneri, mevcut girdilerin doğruluğuna bağlıdır. Malzeme fiyatı veya iş kapsamı değişirse teklif yeniden hesaplanmalıdır." },
  "markup-ve-marj-farki": { heading: "Hangi yüzdeyi kullanıyorsun?", items: ["'Maliyete %30 ekleyeceğim' diyorsan bu markup hesabıdır: 20.000 × 1,30 = 26.000 TL.", "'Satışın %30'u kâr olsun' diyorsan bu marj hesabıdır: 20.000 ÷ 0,70 ≈ 28.571 TL.", "26.000 TL satışta 6.000 TL kâr oluşur; 6.000 ÷ 26.000 ≈ %23,08 marjdır."], caution: "İki yöntem de matematiksel olarak geçerlidir; hedefin hangisi olduğunu karıştırmak fiyatı yanlış yorumlatır." },
  "iscilik-maliyeti-nasil-hesaplanir": { heading: "İş gününü doğru saymak için", items: ["Usta ve yardımcıyı ayrı satırda, kendi günlük işletme maliyetleriyle hesapla.", "Ulaşım ve malzeme alma süresi iş gününe giriyorsa tahmini süreyi buna göre belirle.", "İş uzadığında ilave günün maliyetini ve teklife etkisini önceden gör."], caution: "Günlük örnek tutarlar ücret standardı değildir. Yasal işveren maliyetleri ve sözleşme koşulları işletmeye göre değişebilir." },
  "boyaci-teklifi-nasil-hazirlanir": { heading: "Keşif ve teklif kontrolü", items: ["Duvar ve tavan alanını ayrı ölç; kapı/pencere düşüm yöntemini tutarlı kullan.", "Kat sayısı, astar ve yüzey düzeltme ihtiyacını yaz; örtücülük değerini kullandığın ürün üzerinden gir.", "Koruma malzemesi, fırça/rulo, yol ve iş gününü ekle; kapsam dışı büyük onarımları belirt."], caution: "22 litre örneği yalnızca belirtilen alan, örtücülük ve fire varsayımıyla geçerlidir. Gerçek tüketim yüzeye ve ürüne göre değişir." },
  "elektrik-isi-nasil-fiyatlandirilir": { heading: "Keşifte kaydet", items: ["Kabloyu kesit ve metraj bazında ayır; tek metre fiyatı bütün kablolar için kullanma.", "Priz, anahtar, sigorta ve buat adetlerini ürün seçimiyle birlikte netleştir.", "Montaj gününü, yardımcı ihtiyacını, sarf ve yol maliyetini ayrıca ekle."], caution: "Elektrik güvenliği ve teknik uygunluk fiyat hesabının dışındadır; işi yürürlükteki teknik kurallara göre yetkin kişi planlamalıdır." },
  "teklifte-odeme-kosullari": { heading: "Açık bir ödeme maddesi için", items: ["Toplam tutar ve ödeme aşamalarının her birindeki tutarı açıkça yaz.", "'Teslim' gibi kilometre taşlarını hangi işlerin tamamlanmasıyla oluşacağını belirt.", "Kapsam değişirse ödeme planının yeniden nasıl ele alınacağını müşteriyle netleştir."], caution: "Örnek %30 avans bir öneri veya hukuki kural değildir. Tarafların anlaşması ve uygulanacak mevzuat esas alınmalıdır." },
  "pazarlikta-ne-kadar-indirim": { heading: "İndirimden önce hesapla", items: ["Minimum kabul marjını belirle; 20.000 TL maliyet ve %20 minimum marj için alt sınır 25.000 TL'dir.", "İstenen indirim alt sınırı geçiyorsa kapsam veya ödeme koşulunu yeniden görüş.", "İndirim sonrası beklenen kâr tutarını da gör; yüzde tek başına nakit ihtiyacını anlatmaz."], caution: "Pazarlık sonucu stratejik nedenlerle alt sınırın altına inilirse bu kararın mali etkisi açıkça görülmelidir." },
};
