import { PageIntro } from "@/components/marketing/shell";
import { legalMetadata, legalName, supportEmail } from "@/lib/marketing/legal";
export const metadata = legalMetadata("Gizlilik ve kişisel veriler", "/gizlilik");
export default function Page() { return <article className="mx-auto max-w-3xl px-5 py-16"><PageIntro eyebrow="Gizlilik · 6 Ekim 2026" title="Verilerini nasıl kullanıyoruz?" description="Hesabında hangi bilgilerin tutulduğunu, kimlerle paylaşıldığını ve silme seçeneklerini burada bulabilirsin."/><div className="mt-12 space-y-10 leading-8 text-[#55555d]">
<section><h2 className="text-2xl font-semibold text-[#1d1d1f]">Hizmeti sunan ve iletişim</h2><p className="mt-3">KaçaYapayım hizmetini {legalName} sunar. Verilerinle ilgili sorularını ve taleplerini <a className="marketing-text-link" href={`mailto:${supportEmail}`}>{supportEmail}</a> adresine gönderebilirsin.</p></section>
<section><h2 className="text-2xl font-semibold text-[#1d1d1f]">Topladığımız bilgiler</h2><p className="mt-3">Kayıt ve giriş sırasında ad, soyad, e-posta, parola doğrulama bilgileri ve oturum kayıtları işlenir. İşletme adı, meslek, şehir, telefon, kâr hedefleri ve maliyet ayarları hesabına bağlı tutulur. Eklediğin müşteriler, iletişim bilgileri, iş adresleri, işler, teklifler, tahsilat kayıtları, giderler, saha notları, fotoğraflar ve belgeler hizmetin çalışması için saklanır. Ekip davetleri, geri bildirimler, teklif görüntüleme ve kabul/red kayıtları da bu kapsamdadır.</p><p className="mt-3">Müşteri ve ekip bilgilerini girerken gerekli bilgilendirmeyi yapmak ve paylaşma yetkisine sahip olmak senin sorumluluğundadır. Gerekli olmayan hassas bilgileri yükleme.</p></section>
<section><h2 className="text-2xl font-semibold text-[#1d1d1f]">Amaçlar ve hukuki sebepler</h2><p className="mt-3">Bilgileri hesabını yönetmek, maliyet ve fiyat hesaplamak, teklif paylaşmak, iş takibi yapmak, destek vermek ve kötüye kullanımı önlemek için işleriz. Hizmetin sunulması için gereken işlemler sözleşmenin kurulması ve ifası; güvenlik işlemleri ilgili kişinin haklarını gözeterek meşru menfaat kapsamında değerlendirilir. Kanunen gerekli işlemler ilgili hukuki yükümlülük kapsamında yürütülür. İsteğe bağlı kullanım ve kampanya ölçümü ayrıca verdiğin izinle etkinleşir; tercihlerini değiştirebilirsin.</p></section>
<section><h2 className="text-2xl font-semibold text-[#1d1d1f]">Erişim ve hizmet sağlayıcıları</h2><p className="mt-3">Kimlik doğrulama, veritabanı ve özel dosya saklama için Supabase; web barındırma için Vercel kullanılır. Supabase projesi Frankfurt bölgesindedir. Hizmet sağlayıcılarının destek ve güvenlik süreçleri kendi politikalarına tabidir. Bu hizmetlerin kullanımı yurt dışındaki altyapılarda veri işlenmesini içerebilir.</p><p className="mt-3">Teklif bağlantısını alan kişi müşteri görünümünü okuyabilir; yalnızca alıcına gönder. İç maliyet ve kâr bilgileri bu görünümde yer almaz. Bağlantıyı kapatabilir veya yenileyebilirsin. Ekip üyeleri yalnızca kendilerine atanan işlerin izin verilen bilgilerine erişir. Çevrim içi ödeme altyapısı kullanılmıyor; tahsilat takibi elle girdiğin kayıtlardan oluşur. İsteğe bağlı sesli yazma tarayıcının konuşma hizmetine ses gönderebilir; KaçaYapayım ses dosyası saklamaz. Kanunen yetkili makamların usulüne uygun talepleri gerektiğinde yerine getirilebilir.</p></section>
<section><h2 className="text-2xl font-semibold text-[#1d1d1f]">Saklama ve silme</h2><p className="mt-3">İşletme, müşteri, iş, teklif ve dosyalar hesabın açık kaldığı sürece tutulur. Hesabını silerken özel dosyalar ve hesaba bağlı işletme kayıtları temizlenir. Dosya temizliği başarısız olursa hesap silme tamamlanmaz; tekrar deneyebilirsin. Kaydedilmemiş tarayıcı taslakları aynı oturumda en fazla 24 saat korunur ve çıkış yaptığın sekmede temizlenir.</p><p className="mt-3">İstek sınırı sayaçları günlük temizlikte 48 saatten eski olduğunda; toplu kullanım, kampanya ve ürün ölçüm kayıtları 90 günden eski olduğunda kaldırılır. Yedeklerdeki kopyalar ve sağlayıcı güvenlik günlükleri kendi saklama döngülerine tabidir; anında silme taahhüdü verilmez. Destek yazışmaları talebin çözümü ve uygulanabilir hukuki yükümlülükler için gerekli süreyle sınırlandırılır.</p></section>
<section><h2 className="text-2xl font-semibold text-[#1d1d1f]">Seçeneklerin ve hakların</h2><p className="mt-3">Ayarlardan bilgilerini düzeltebilir, kayıtlarını dışa aktarabilir, diğer cihazlardaki oturumları kapatabilir ve parolanı doğrulayarak hesabını silebilirsin. Verilerinin işlenip işlenmediğini öğrenme; işlenmişse bilgi isteme; amaçlarını ve aktarıldığı kişileri öğrenme; yanlış bilgileri düzeltme; uygulanabilir koşullarda silme; bu işlemlerin alıcılara bildirilmesini isteme; otomatik analiz sonucuna itiraz etme ve hukuka aykırı işleme nedeniyle zararın giderilmesini talep etme hakların vardır. Başvurunu destek adresine gönder; talebin güvenliği için kimliğini doğrulamamız gerekebilir.</p></section>
</div></article>; }
