begin;
-- Only this rolled-back disposable fixture can bypass the hosted Storage API guard.
set local storage.allow_delete_query = 'true';
do $$ begin
 if has_function_privilege('anon','public.update_my_settings(text,text,text,text,text,text,numeric,numeric)','execute') then raise exception 'Owner settings exposed to anon';end if;
end $$;
do $$ declare a uuid:=gen_random_uuid();b uuid:=gen_random_uuid();ba uuid;bb uuid;c uuid;j uuid;q uuid;r uuid;begin
 insert into auth.users(id,email,raw_user_meta_data) values(a,'audit-a-'||a||'@example.test','{}'),(b,'audit-b-'||b||'@example.test','{}');
 insert into public.businesses(owner_id,name,profession,onboarding_completed,onboarding_step) values(a,'Audit A','Camcı',true,4) returning id into ba;
 insert into public.businesses(owner_id,name,profession,onboarding_completed,onboarding_step) values(b,'Audit B','Camcı',true,4) returning id into bb;
 insert into public.subscriptions(business_id,plan_id,status,provider,provider_subscription_id,current_period_end) values(ba,'usta','active','test',a::text,now()+interval '1 month');
 perform set_config('request.jwt.claims',jsonb_build_object('sub',a,'role','authenticated','aal','aal1')::text,true);
 insert into public.customers(business_id,name) values(ba,'Audit customer') returning id into c;
 j:=public.save_manual_job(null,c,'Audit job','','[{"name":"Material","category":"material","quantity":1,"unit_cost":100}]');
 perform public.save_job_pricing(j,30,20,150,false);
 q:=public.save_quote_with_tax_rate(null,j,'ready','Original','','[{"name":"Scope"}]','[]','','',current_date+7,'',null,false,'excluded',20);
 r:=public.copy_my_quote(q,true);
 if (select status from public.quotes where id=q)<>'ready' then raise exception 'Draft revision closed original';end if;
 perform set_config('test.a',a::text,true);perform set_config('test.b',b::text,true);perform set_config('test.ba',ba::text,true);perform set_config('test.bb',bb::text,true);
 perform set_config('test.j',j::text,true);perform set_config('test.q',q::text,true);perform set_config('test.r',r::text,true);
 perform set_config('test.oldtoken',(select public_token::text from public.quotes where id=q),true);
end $$;
set local role authenticated;
do $$ declare t uuid;blocked boolean;begin
 t:=public.save_quote_with_tax_rate(current_setting('test.r')::uuid,current_setting('test.j')::uuid,'ready','Revision','','[{"name":"New scope"}]','[]','','',current_date+7,'',150,false,'excluded',20);
 if not exists(select 1 from public.quotes where id=current_setting('test.q')::uuid and status='cancelled') then raise exception 'Published revision left original open';end if;
 insert into public.job_payments(business_id,job_id,amount,paid_at,method,note) values(current_setting('test.ba')::uuid,current_setting('test.j')::uuid,10.12,current_date,'cash','First'),(current_setting('test.ba')::uuid,current_setting('test.j')::uuid,20.23,current_date,'bank','Second');
 if public.get_my_payment_total(current_setting('test.j')::uuid)<>30.35 then raise exception 'Payment precision';end if;
 blocked:=false;begin perform public.manage_quote_link(current_setting('test.q')::uuid,'rotate');exception when raise_exception then blocked:=true;end;
 if not blocked then raise exception 'Superseded link revived';end if;
 perform set_config('test.revtoken',(select public_token::text from public.quotes where id=current_setting('test.r')::uuid),true);
 t:=public.manage_quote_link(current_setting('test.r')::uuid,'rotate');perform set_config('test.newtoken',t::text,true);
 perform set_config('request.jwt.claims',jsonb_build_object('sub',current_setting('test.b'),'role','authenticated','aal','aal1')::text,true);
 if exists(select 1 from public.job_payments where job_id=current_setting('test.j')::uuid) or public.get_my_payment_total(current_setting('test.j')::uuid)<>0 then raise exception 'Cross-business payments readable';end if;
 blocked:=false;begin insert into public.job_payments(business_id,job_id,amount,paid_at,method) values(current_setting('test.bb')::uuid,current_setting('test.j')::uuid,1,current_date,'cash');exception when insufficient_privilege then blocked:=true;end;
 if not blocked then raise exception 'Foreign job payment accepted';end if;
 blocked:=false;begin perform public.manage_quote_link(current_setting('test.r')::uuid,'revoke');exception when raise_exception then blocked:=true;end;
 if not blocked then raise exception 'Foreign link changed';end if;
 delete from public.job_payments where job_id=current_setting('test.j')::uuid;
 perform set_config('request.jwt.claims',jsonb_build_object('sub',current_setting('test.a'),'role','authenticated','aal','aal1')::text,true);
 if public.get_my_payment_total(current_setting('test.j')::uuid)<>30.35 then raise exception 'Foreign payment deletion';end if;
 perform public.manage_quote_link(current_setting('test.r')::uuid,'revoke');
end $$;
reset role;
do $$ declare blocked boolean; t uuid;begin
 if public.get_public_quote_details(current_setting('test.oldtoken')::uuid) is not null then raise exception 'Old revision visible';end if;
 if public.get_public_quote_details(current_setting('test.revtoken')::uuid) is not null then raise exception 'Rotated token visible';end if;
 select public_token into t from public.quotes where id=current_setting('test.r')::uuid;
 if public.get_public_quote_details(t) is not null then raise exception 'Revoked quote visible';end if;
 blocked:=false;begin perform public.respond_to_package_quote(t,'accept',null,null);exception when raise_exception then blocked:=true;end;
 if not blocked then raise exception 'Revoked quote accepted';end if;
 perform public.manage_quote_link(current_setting('test.r')::uuid,'rotate');
 select public_token into t from public.quotes where id=current_setting('test.r')::uuid;
 if public.get_public_quote_details(t) is null then raise exception 'New link unavailable';end if;
 perform public.respond_to_package_quote(t,'accept',null,null);
 if (select count(*) from public.notifications where quote_id=current_setting('test.r')::uuid)<>1 then raise exception 'Decision notification missing';end if;
 -- Repeated status updates do not duplicate notifications.
 update public.quotes set status='accepted' where id=current_setting('test.r')::uuid;
 if (select count(*) from public.notifications where quote_id=current_setting('test.r')::uuid)<>1 then raise exception 'Duplicate notification';end if;
 insert into storage.objects(bucket_id,name,metadata) values('business-assets',current_setting('test.a')||'/existing',jsonb_build_object('size',104857590));
 if public.reserve_upload(current_setting('test.a')::uuid,current_setting('test.a')||'/job/file',30) then raise exception 'Quota exceeded';end if;
 delete from storage.objects where name=current_setting('test.a')||'/existing';
 if public.reserve_upload(current_setting('test.a')::uuid,current_setting('test.b')||'/file',1) then raise exception 'Foreign upload reserved';end if;
 if not public.reserve_upload(current_setting('test.a')::uuid,current_setting('test.a')||'/job/file',100) then raise exception 'Valid upload reservation rejected';end if;
 insert into auth.mfa_factors(id,user_id,factor_type,status,created_at,updated_at) values(gen_random_uuid(),current_setting('test.a')::uuid,'totp','verified',now(),now());
end $$;
set local role authenticated;
do $$ declare blocked boolean;begin
 if private.mfa_satisfied() then raise exception 'AAL1 bypassed verified factor';end if;
 blocked:=false;begin perform public.update_my_settings('Changed','Name','Changed business','','','',30,20);exception when raise_exception then blocked:=true;end;
 if not blocked then raise exception 'Settings updated without MFA';end if;
 if exists(select 1 from public.businesses where id=current_setting('test.ba')::uuid) then raise exception 'MFA policy readable at AAL1';end if;
 blocked:=false;begin perform public.copy_my_job(current_setting('test.j')::uuid);exception when raise_exception then blocked:=true;end;
 if not blocked then raise exception 'MFA RPC bypass';end if;
 if public.get_my_payment_total(current_setting('test.j')::uuid)<>0 then raise exception 'MFA total bypass';end if;
 blocked:=false;begin perform public.get_my_archive_page('quotes',null,now());exception when raise_exception then blocked:=true;end;
 if not blocked then raise exception 'MFA archive bypass';end if;
 perform set_config('request.jwt.claims',jsonb_build_object('sub',current_setting('test.a'),'role','authenticated')::text,true);
 if private.mfa_satisfied() then raise exception 'Missing AAL bypass';end if;
 blocked:=false;begin perform private.require_mfa();exception when raise_exception then blocked:=true;end;
 if not blocked then raise exception 'Missing AAL guard bypass';end if;
 perform set_config('request.jwt.claims',jsonb_build_object('sub',current_setting('test.a'),'role','authenticated','aal','aal2')::text,true);
 if not private.mfa_satisfied() or not exists(select 1 from public.businesses where id=current_setting('test.ba')::uuid) then raise exception 'AAL2 rejected';end if;
 declare t text;records jsonb;item jsonb;extra uuid;new_job uuid;again uuid;begin
  foreach t in array array['profiles','businesses','business_preferences','business_branding','business_profession_settings','business_cost_items','customers','jobs','painter_job_details','job_cost_breakdown','actual_job_costs','quotes','quote_items','quote_exclusions','quote_templates','service_package_groups','quote_decision_history','work_entries','job_payments','notifications','job_viewers','subscriptions'] loop
   begin records:=public.get_my_archive_page(t,null,now());exception when others then raise exception 'Archive table %: %',t,sqlerrm;end;
   for item in select * from jsonb_array_elements(records) loop
    if item->'record'?'public_token' or item->'record'?'token_hash' then raise exception 'Archive includes access secrets';end if;
    if item->'record'->>'business_id'=current_setting('test.bb') then raise exception 'Archive includes foreign business';end if;
   end loop;
  end loop;
  blocked:=false;begin perform public.get_my_archive_page('auth.users',null,now());exception when raise_exception then blocked:=true;end;
  if not blocked then raise exception 'Archive table allowlist bypass';end if;
  insert into public.work_entries(business_id,job_id,kind,title,status,amount) values(current_setting('test.ba')::uuid,current_setting('test.j')::uuid,'extra_work','Extra','approved',300) returning id into extra;
  new_job:=public.save_approved_extra_job(extra,'Extra job','','[{"name":"Cost","category":"material","quantity":1,"unit_cost":100}]');
  again:=public.save_approved_extra_job(extra,'Extra job','','[{"name":"Cost","category":"material","quantity":1,"unit_cost":100}]');
  if new_job<>again or new_job=current_setting('test.j')::uuid then raise exception 'Extra job idempotency';end if;
  if (select status from public.quotes where id=current_setting('test.r')::uuid)<>'accepted' then raise exception 'Extra job changed accepted quote';end if;
 end;
 update public.notifications set read_at=now() where quote_id=current_setting('test.r')::uuid;
 if exists(select 1 from public.notifications where quote_id=current_setting('test.r')::uuid and read_at is null) then raise exception 'Notification read not saved';end if;
 blocked:=false;begin insert into storage.objects(bucket_id,name,metadata) values('business-assets',current_setting('test.a')||'/bypass','{}');exception when insufficient_privilege then blocked:=true;end;
 if not blocked then raise exception 'Storage direct upload bypass';end if;
end $$;
reset role;
do $$begin
 insert into storage.objects(bucket_id,name,metadata) select 'business-assets',current_setting('test.a')||'/count-test/'||n,jsonb_build_object('size',1) from generate_series(1,1000)n;
 if public.reserve_upload(current_setting('test.a')::uuid,current_setting('test.a')||'/count-test/overflow',1) then raise exception 'File count quota exceeded';end if;
 delete from storage.objects where name like current_setting('test.a')||'/count-test/%';
 if (select count(*) from public.quote_decision_history where quote_id=current_setting('test.r')::uuid)<>1 then raise exception 'Decision snapshot missing or repeated';end if;
 if not exists(select 1 from public.quote_decision_history where quote_id=current_setting('test.r')::uuid and content_hash=encode(extensions.digest(snapshot::text,'sha256'),'hex') and snapshot->>'title'='Revision') then raise exception 'Decision content hash mismatch';end if;
 if has_table_privilege('authenticated','public.quote_decision_history','UPDATE') or has_table_privilege('authenticated','public.quote_decision_history','DELETE') then raise exception 'Decision history mutable by owner';end if;
 insert into public.work_entries(business_id,job_id,quote_id,kind,title) values(current_setting('test.ba')::uuid,current_setting('test.j')::uuid,current_setting('test.r')::uuid,'revision_request','Test request');
 if not exists(select 1 from public.notifications where business_id=current_setting('test.ba')::uuid and event_key like 'revision_request:%') then raise exception 'Revision request notification missing';end if;
 update public.signup_settings set enabled=false;
 if public.before_user_created('{}')->'error'->>'http_code'<>'403' then raise exception 'Closed signup accepted';end if;
 update public.signup_settings set enabled=true;
 if public.before_user_created('{}')<>'{}'::jsonb then raise exception 'Open signup rejected';end if;
 perform public.set_quote_access_code(current_setting('test.r')::uuid,'123456');
 if not public.verify_quote_access_code((select public_token from public.quotes where id=current_setting('test.r')::uuid),'123456') or public.verify_quote_access_code((select public_token from public.quotes where id=current_setting('test.r')::uuid),'654321') then raise exception 'Access code verification mismatch';end if;
 if has_function_privilege('authenticated','public.verify_quote_access_code(uuid,text)','execute') or has_table_privilege('authenticated','public.quote_access_controls','SELECT') then raise exception 'Access code hash exposed';end if;
 if public.begin_account_deletion(current_setting('test.a')::uuid) then raise exception 'Deletion raced an upload';end if;
 delete from public.storage_upload_reservations where user_id=current_setting('test.a')::uuid;
 if not public.begin_account_deletion(current_setting('test.a')::uuid) then raise exception 'Deletion lock missing';end if;
 if public.reserve_upload(current_setting('test.a')::uuid,current_setting('test.a')||'/job/new',100) then raise exception 'Upload accepted during deletion';end if;
 if position('private.mfa_satisfied()' in pg_get_functiondef('private.get_assigned_jobs()'::regprocedure))=0 then raise exception 'Team reader bypasses MFA';end if;
 if has_function_privilege('anon','public.manage_quote_link(uuid,text)','execute') or has_function_privilege('authenticated','public.reserve_upload(uuid,text,bigint)','execute') then raise exception 'RPC permission leak';end if;
 insert into public.request_rate_limits values('audit',repeat('a',64),0,1,now()-interval '49 hours');
 insert into public.analytics_daily_events values(current_date-91,'audit','/','unknown',1);
 perform public.run_data_retention();
 if exists(select 1 from public.request_rate_limits where scope='audit') or exists(select 1 from public.analytics_daily_events where event_name='audit') then raise exception 'Retention boundary';end if;
 if not exists(select 1 from cron.job where jobname='kacayapayim-data-retention' and command='select public.run_data_retention()') then raise exception 'Retention schedule missing';end if;
end $$;
rollback;
select 'PASS: revision publication/revocation, token rotation, foreign-owner denial, payment precision, quota reservation, MFA AAL1/AAL2/missing claim, notification idempotency, storage bypass denial, retention boundaries; fixtures rolled back' as result;
