import { redirect } from "next/navigation";
import { requireViewer } from "@/lib/viewer";
import { createServiceClient } from "@/lib/supabase/admin";
export const metadata={title:'Ürün Ölçümleri'};
export default async function AnalyticsPage(){
 const viewer=await requireViewer();const service=createServiceClient();const {data:admin}=await service.from('platform_admins').select('user_id').eq('user_id',viewer.id).maybeSingle();if(!admin)redirect('/dashboard');
 const [{data:cohorts,error},{data:campaigns}]=await Promise.all([service.rpc('get_product_cohorts',{}),service.from('marketing_campaign_daily').select('*').order('day',{ascending:false}).limit(100)]);
 if(error)throw new Error('Ürün ölçümleri yüklenemedi.');
 return <div className="mx-auto max-w-5xl"><h1 className="text-3xl font-semibold">Ürün ölçümleri</h1><p className="mt-3 text-sm text-[#6E6E73]">Aktivasyon: en az bir teklif oluşturma. Tekrar kullanım, ölçüm etkinleştirildikten sonraki işletme olaylarına dayanır. Yeni kohortlarda süre dolmadan oran hesaplanmaz.</p><div className="mt-6 overflow-auto rounded-xl border bg-white"><table className="w-full text-left text-sm"><thead><tr>{['Kayıt ayı','İşletme','İlk teklif','1–7 gün tekrar','8–30 gün tekrar'].map(s=><th key={s} className="p-4">{s}</th>)}</tr></thead><tbody>{cohorts?.map(c=><tr key={c.cohort} className="border-t"><td className="p-4">{c.cohort}</td><td className="p-4">{c.businesses}</td><td className="p-4">{c.activated}</td><td className="p-4">{c.eligible7?`${c.repeated7}/${c.eligible7}`:'Henüz ölçülemez'}</td><td className="p-4">{c.eligible30?`${c.repeated30}/${c.eligible30}`:'Henüz ölçülemez'}</td></tr>)}</tbody></table></div><h2 className="mt-8 text-xl font-semibold">Son kampanya olayları</h2><div className="mt-4 space-y-2">{campaigns?.map(c=><div key={[c.day,c.event_name,c.path,c.channel,c.medium,c.campaign].join(':')} className="rounded-xl border bg-white p-4 text-sm">{c.day} · {c.channel} / {c.medium} · {c.campaign} · {c.event_name}: <strong>{c.hits}</strong></div>)}</div></div>;
}
