import {useCallback,useState} from 'react';
import {Text} from 'react-native';
import {router,useFocusEffect,useLocalSearchParams} from 'expo-router';
import {Button,Card,Choice,Field,Notice,Row,Screen,SectionTitle} from '@/src/components/ui';
import {useAppSession} from '@/src/lib/session';
import {db} from '@/src/lib/supabase';
import {money,numberFromInput} from '@/src/lib/format';
import {setDeviceReminder,cancelDeviceReminder} from '@/src/lib/reminders';
import type {Database} from '@kacayapayim/core/types';
type Entry=Database['public']['Tables']['work_entries']['Row'];
const kinds={note:'Saha notu',followup:'Takip',visit:'Keşif',expense:'Gider',extra_work:'Ek iş'} as const;
export default function Work(){
 const {business}=useAppSession();const {jobId}=useLocalSearchParams<{jobId?:string}>();
 const [entries,setEntries]=useState<Entry[]>([]);const [kind,setKind]=useState<keyof typeof kinds>('note');const [title,setTitle]=useState('');const [note,setNote]=useState('');const [amount,setAmount]=useState('');const [when,setWhen]=useState('');const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [message,setMessage]=useState('');
 const load=useCallback(async()=>{if(!business)return;let query=db().from('work_entries').select('*').eq('business_id',business.id);if(jobId)query=query.eq('job_id',jobId);const rows:Entry[]=[];for(let offset=0;;offset+=500){const {data,error:readError}=await query.order('created_at',{ascending:false}).order('id').range(offset,offset+499);if(readError)throw new Error('Kayıtlar yüklenemedi.');rows.push(...data);if(data.length<500)break;}setEntries(rows);},[business,jobId]);
 useFocusEffect(useCallback(()=>{void load().catch(()=>setError('Kayıtlar yüklenemedi. Yenilemeyi dene.'));},[load]));
 async function save(){if(!business||busy)return;setError('');setMessage('');const total=amount.trim()?numberFromInput(amount):null;const scheduled=when.trim()?new Date(when.trim().replace(' ','T')+':00+03:00'):null;if(!title.trim()||title.length>160||note.length>2000||(kind==='expense'&&(!jobId||total===null))||(total!==null&&(!Number.isFinite(total)||total<0))||(scheduled&&!Number.isFinite(scheduled.getTime()))){setError('Başlığı, tutarı ve tarihi kontrol et. Gideri iş detayından ekle.');return;}setBusy(true);try{const {error:saveError}=await db().from('work_entries').insert({business_id:business.id,job_id:jobId??null,kind,title:title.trim(),note:note.trim(),amount:total,scheduled_at:scheduled?.toISOString()??null});if(saveError)throw saveError;setTitle('');setNote('');setAmount('');setWhen('');await load();}catch{setError('Kayıt kaydedilemedi. Alanların korunuyor.');}finally{setBusy(false);}}
 return <Screen title="İş takibi" subtitle="Saha notları, keşif ve giderler"><Button title="Yenile" quiet onPress={()=>{void load().catch(()=>setError('Kayıtlar yüklenemedi.'));}}/>{!!error&&<Notice error>{error}</Notice>}{!!message&&<Notice>{message}</Notice>}{entries.map(e=><Card key={e.id}><Row title={e.title} subtitle={`${kinds[e.kind as keyof typeof kinds]??'Kayıt'} · ${e.status==='open'?'Bekliyor':'Tamamlandı'}`} right={e.amount!==null?money(e.amount):undefined}/>{!!e.note&&<Text>{e.note}</Text>}{!!e.scheduled_at&&<Text>{new Date(e.scheduled_at).toLocaleString('tr-TR',{timeZone:'Europe/Istanbul'})}</Text>}{e.status==='open'&&<Button disabled={busy} title="Tamamlandı işaretle" quiet onPress={async()=>{setBusy(true);try{const {error:updateError}=await db().from('work_entries').update({status:'done'}).eq('id',e.id).eq('business_id',business!.id);if(updateError)throw updateError;await cancelDeviceReminder(e.id);await load();}catch{setError('Durum güncellenemedi.');}finally{setBusy(false);}}}/>}{e.status==='open'&&e.scheduled_at&&<Button title="Bu cihazda hatırlat" quiet onPress={async()=>{try{await setDeviceReminder(e.id,e.scheduled_at!);setMessage('Bu cihaz için hatırlatma kuruldu.');}catch(cause){setError(cause instanceof Error?cause.message:'Hatırlatma kurulamadı.');}}}/>}</Card>)}<SectionTitle>Kayıt ekle</SectionTitle><Card>{Object.entries(kinds).filter(([k])=>jobId||k!=='expense').map(([k,label])=><Choice key={k} title={label} selected={kind===k} onPress={()=>setKind(k as keyof typeof kinds)}/>)}<Field label="Başlık" value={title} onChangeText={setTitle}/><Field label="Not" value={note} onChangeText={setNote} multiline/>{['expense','extra_work'].includes(kind)&&<Field label="Tutar (TL)" value={amount} onChangeText={setAmount} keyboardType="decimal-pad"/>}<Field label="İstanbul saati (YYYY-AA-GG SS:DD)" value={when} onChangeText={setWhen} placeholder="2026-10-06 14:30"/><Button title={busy?'Kaydediliyor…':'Kaydet'} disabled={busy} onPress={()=>{void save();}}/></Card><Notice>İşe bağlı giderler gerçekleşen maliyete otomatik eklenir. Cihaz hatırlatmaları burada seçtiğin tarihler içindir.</Notice><Button title="Geri" quiet onPress={()=>router.back()}/></Screen>;
}
