"use client";
import {useEffect,useState,useRef} from "react";
import {useRouter} from "next/navigation";
import {CustomerSelect} from "./customer-select";
import {saveManualJob,type ManualLine} from "@/app/actions/manual-jobs";
import {useDraft} from "@/components/draft-provider";
import {formatMoney} from "@/lib/costs/format";
import {parsePrice,parseQuantity} from "@/lib/money";
import type {CustomerChoice} from "@/app/actions/jobs";
import type {Job,BusinessCostItem} from "@/types/database";
type Line={key:number;name:string;category:ManualLine["category"];quantity:string;unit_cost:string};
const control="mt-2 min-h-12 w-full rounded-xl border border-[#d2d2d7] bg-white px-3 text-base";
function restoreLines(values:unknown[]):Line[]{return values.slice(0,60).map((value,i)=>{const l=value as Record<string,unknown>;return {key:i,name:String(l?.name||"").slice(0,160),category:["material","labor","other"].includes(String(l?.category))?l.category as Line["category"]:"other",quantity:String(l?.quantity??1),unit_cost:String(l?.unit_cost??0)};});}
export function ManualJobForm({customers,selectedCustomer,job,fromCalculator=false,costs=[],sourceExtraId,initialTitle="",initialDescription=""}:{customers:CustomerChoice[];selectedCustomer:CustomerChoice|null;job?:Job|null;fromCalculator?:boolean;costs?:BusinessCostItem[];sourceExtraId?:string;initialTitle?:string;initialDescription?:string}){
 const router=useRouter();const nextKey=useRef(100);const [title,setTitle]=useState(job?.title||initialTitle);const [description,setDescription]=useState(job?.description||initialDescription);const [customer,setCustomer]=useState(selectedCustomer);
 const [lines,setLines]=useState<Line[]>(restoreLines(Array.isArray(job?.input_data.lines)?job.input_data.lines:[{name:"",category:"material",quantity:1,unit_cost:0}]));
 const [margin,setMargin]=useState<number|null>(null);const [busy,setBusy]=useState(false);const [error,setError]=useState("");const [online,setOnline]=useState(true);
 useEffect(()=>{const update=()=>setOnline(navigator.onLine);update();window.addEventListener("online",update);window.addEventListener("offline",update);return()=>{window.removeEventListener("online",update);window.removeEventListener("offline",update);};},[]);
 const draft=useDraft("manual:"+(job?.id||sourceExtraId||"new"),{title,description,customer,lines,margin},s=>{if(typeof s.title!=="string"||!Array.isArray(s.lines))return;setTitle(s.title);setDescription(String(s.description||""));setCustomer(selectedCustomer||s.customer);setLines(restoreLines(s.lines));if(typeof s.margin==="number"&&s.margin>=1&&s.margin<=90)setMargin(s.margin);});
 useEffect(()=>{if(!fromCalculator)return;try{const raw=sessionStorage.getItem("ky:calculator-result");const s=raw&&JSON.parse(raw);if(s&&Date.now()-s.at<86400000&&Number.isFinite(s.cost)&&s.cost>0&&s.cost<1e12){setTitle("Hesaplayıcıdan oluşturulan iş");setLines(restoreLines([{name:"Hesaplanan toplam maliyet",category:"other",quantity:1,unit_cost:Math.round(s.cost*100)/100}]));setDescription("Hesaplayıcıdan aktarıldı. Teklif öncesinde maliyet ve kapsamı kontrol et.");if(Number.isFinite(s.margin)&&s.margin>=1&&s.margin<=90)setMargin(s.margin);}}catch{}},[fromCalculator]);
 const payload=lines.map(l=>({name:l.name,category:l.category,quantity:parseQuantity(l.quantity),unit_cost:parsePrice(l.unit_cost)}));
 const valid=payload.every(l=>l.name.trim()&&l.quantity!==null&&l.unit_cost!==null&&l.unit_cost<=1e9);
 const total=payload.reduce((sum,l)=>sum+Math.round((l.quantity||0)*(l.unit_cost||0)*100),0)/100;
 const favorites=costs.filter(c=>c.is_active).sort((a,b)=>Number(!!b.is_favorite)-Number(!!a.is_favorite));
 function update(key:number,patch:Partial<Line>){setLines(a=>a.map(l=>l.key===key?{...l,...patch}:l));}
 function add(cost?:BusinessCostItem){if(lines.length>=60)return;setLines(a=>[...a,{key:nextKey.current++,name:cost?.name||"",category:cost?.category==="material"?"material":cost?.category==="labor"?"labor":"other",quantity:"1",unit_cost:String(cost?.unit_cost||0)}]);}
 function copy(line:Line){if(lines.length>=60)return;setLines(current=>[...current,{...line,key:nextKey.current++}]);}
 async function save(){if(busy||!valid||!online)return;setBusy(true);setError("");try{const r=await saveManualJob({sourceExtraId,id:job?.id||null,customerId:customer?.id||null,title,description,lines:payload as ManualLine[]});if(!r.ok||!r.id){setError(r.error||"Kayıt tamamlanamadı.");return;}draft.clear();if(fromCalculator)sessionStorage.removeItem("ky:calculator-result");router.push(`/jobs/${r.id}/pricing${margin!==null?`?target_margin=${margin}`:""}`);router.refresh();}catch{setError("Bağlantı kurulamadı. Taslağın korunuyor; yeniden Kaydet ile dene.");}finally{setBusy(false);}}
 return <div className="mx-auto max-w-3xl"><h1 className="text-3xl font-semibold">Genel iş hesabı</h1><p className="mt-2 text-sm text-[#6e6e73]">Malzeme, işçilik ve diğer maliyetlerini ekle. Miktarda virgülle en fazla 3, tutarda 2 ondalık basamak kullanabilirsin.</p>{draft.notice&&<p role="status" className="mt-3 text-sm text-[#0071e3]">{draft.notice}</p>}{!online&&<p role="status" className="mt-3 rounded-xl bg-amber-50 p-3 text-sm text-amber-900">Çevrim dışısın. Bu açık sekmedeki taslak korunuyor; bağlantı gelince kendin Kaydet düğmesine bas. Sekmeyi kapatmadan önce bağlantını kontrol et.</p>}
 <form onSubmit={e=>{e.preventDefault();void save();}} className="mt-6 space-y-5"><div className="rounded-2xl border bg-white p-5"><CustomerSelect initialCustomers={customers} selected={customer} onSelect={setCustomer}/><label className="mt-5 block text-sm font-medium">İş başlığı<input required maxLength={160} value={title} onChange={e=>setTitle(e.target.value)} className={control}/></label><label className="mt-4 block text-sm font-medium">Açıklama<textarea maxLength={2000} rows={3} value={description} onChange={e=>setDescription(e.target.value)} className={`${control} py-3`}/></label></div>
 {favorites.length>0&&<label className="block rounded-2xl border bg-white p-5 text-sm font-medium">Kayıtlı maliyetlerden hızlı ekle<select disabled={lines.length>=60} value="" onChange={e=>{const c=costs.find(c=>c.id===e.target.value);if(c)add(c);}} className={control}><option value="">Maliyet seç</option>{favorites.map(c=><option key={c.id} value={c.id}>{c.is_favorite?"★ ":""}{c.name} · {formatMoney(c.unit_cost)}</option>)}</select></label>}
 {lines.map((l,i)=><details key={l.key} open={i===lines.length-1||!l.name.trim()} className="rounded-2xl border bg-white p-5"><summary className="min-h-11 cursor-pointer font-semibold">{i+1}. {l.name||"Yeni maliyet"} <span className="float-right text-sm">{formatMoney((parseQuantity(l.quantity)||0)*(parsePrice(l.unit_cost)||0))}</span></summary><div className="mt-3"><label className="block text-sm">Kalem adı<input required maxLength={160} value={l.name} onChange={e=>update(l.key,{name:e.target.value})} className={control}/></label><div className="mt-3 grid gap-3 sm:grid-cols-3"><label className="text-sm">Tür<select value={l.category} onChange={e=>update(l.key,{category:e.target.value as Line["category"]})} className={control}><option value="material">Malzeme</option><option value="labor">İşçilik</option><option value="other">Diğer</option></select></label><label className="text-sm">Miktar<input required inputMode="decimal" maxLength={20} value={l.quantity} aria-invalid={parseQuantity(l.quantity)===null} onChange={e=>update(l.key,{quantity:e.target.value})} className={control}/></label><label className="text-sm">Birim maliyet (TL)<input required inputMode="decimal" maxLength={24} value={l.unit_cost} aria-invalid={parsePrice(l.unit_cost)===null} onChange={e=>update(l.key,{unit_cost:e.target.value})} className={control}/></label></div><button type="button" disabled={lines.length>=60} onClick={()=>copy(l)} className="mt-3 min-h-11 px-3 text-sm text-[#0071e3] disabled:opacity-50">Bu maliyeti kopyala</button><button type="button" disabled={lines.length===1} onClick={()=>setLines(a=>a.filter(v=>v.key!==l.key))} className="mt-3 min-h-11 px-3 text-sm text-[#b42318]">Bu maliyeti sil</button></div></details>)}
 <button type="button" disabled={lines.length>=60} onClick={()=>add()} className="min-h-11 rounded-xl border bg-white px-4">Maliyet ekle ({lines.length}/60)</button>{error&&<p role="alert" className="text-sm text-[#b42318]">{error}</p>}
 <div className="sticky bottom-[calc(5rem+env(safe-area-inset-bottom))] rounded-2xl border border-[#d7e8fa] bg-[#eef6ff] p-4 shadow-lg sm:bottom-3"><div className="flex items-center justify-between gap-3"><p className="text-sm">Toplam maliyet</p><p className="text-2xl font-semibold">{formatMoney(total)}</p></div>{!valid&&<p className="mt-2 text-xs text-[#b42318]">Her maliyetin adını, pozitif miktarını ve geçerli birim tutarını tamamla.</p>}<button disabled={busy||!online||!valid||total<=0} className="mt-3 min-h-12 w-full rounded-xl bg-[#0071e3] font-semibold text-white disabled:opacity-50">{busy?"Kaydediliyor…":"Kaydet ve fiyatını belirle"}</button></div>
 </form></div>;
}
