"use client";
import { useState } from "react";
import { useRouter } from "next/navigation";
import { parseCsv } from "@/lib/csv";
import { importCustomers } from "@/app/actions/import-customers";
import { Dialog } from "@/components/ui/dialog";
export function CustomerImport(){
 const router=useRouter();const [open,setOpen]=useState(false);const [rows,setRows]=useState<Record<string,string>[]>([]);const [busy,setBusy]=useState(false);const [message,setMessage]=useState('');
 return <div className="mb-5 flex flex-wrap gap-2"><a href="/api/export/customers" className="inline-flex min-h-11 items-center rounded-xl border border-[#e5e5e9] bg-white px-4 text-sm">CSV Dışa Aktar</a><button onClick={()=>{setOpen(true);setMessage('');setRows([]);}} className="min-h-11 rounded-xl border border-[#e5e5e9] bg-white px-4 text-sm">CSV İçeri Aktar</button>{open&&<Dialog title="Müşteri listesini içeri aktar" onClose={()=>setOpen(false)} busy={busy}><p className="text-sm leading-6 text-[#6E6E73]">Başlıklar: name, phone, email, company_name, city, district, address, notes. Yalnızca name zorunlu. Bir seferde en fazla 100 müşteri; aynı telefonla kayıtlar tekrar eklenmez.</p><label className="mt-4 block text-sm font-medium">CSV dosyası<input type="file" accept=".csv,text/csv" className="mt-3 block min-h-11 w-full" onChange={async e=>{setRows([]);setMessage('');const file=e.target.files?.[0];if(!file)return;if(file.size>512*1024){setMessage('Dosya en fazla 512 KB olabilir.');return;}try{const parsed=parseCsv(await file.text());const headers=parsed.shift()?.map(h=>h.trim().toLowerCase())??[];if(!headers.includes('name'))throw new Error('name başlığı bulunamadı.');if(parsed.length>100||!parsed.length)throw new Error('Dosyada 1–100 müşteri olmalı.');setRows(parsed.map(row=>Object.fromEntries(headers.map((h,i)=>[h,row[i]??'']))));}catch(error){setMessage(error instanceof Error?error.message:'Dosya okunamadı.');}}}/></label>{rows.length>0&&<><p className="mt-4 text-sm font-semibold">{rows.length} müşteri aktarılacak</p><ul className="mt-2 max-h-40 overflow-auto text-sm">{rows.slice(0,10).map((r,i)=><li key={i} className="py-1">{r.name} · {r.phone||'Telefon yok'}</li>)}</ul><button disabled={busy} onClick={async()=>{if(busy)return;setBusy(true);try{const r=await importCustomers(rows);setMessage(`${r.created} müşteri eklendi.${r.failures.length?' Sorunlar: '+r.failures.map(f=>`Satır ${f.row}: ${f.error}`).join(' / '):''}`);setRows([]);router.refresh();}catch{setMessage('Aktarım tamamlanamadı. Listeyi kontrol edip tekrar dene.');}finally{setBusy(false);}}} className="mt-4 min-h-12 w-full rounded-xl bg-[#0071E3] text-white">{busy?'Aktarılıyor…':'Gösterilen Müşterileri Ekle'}</button></>}{message&&<p role="status" className="mt-4 text-sm">{message}</p>}</Dialog>}</div>;
}
