import Link from "next/link";
import { ArrowLeft } from "lucide-react";
import { QuotePreview } from "@/components/quotes/quote-preview";
import { Card } from "@/components/ui";
import { demoQuotePreview } from "@/lib/demo/data";

export const metadata = { title: "Demo Yeni Teklif" };
export default function DemoNewQuotePage() {
  return <div className="mx-auto max-w-[1280px]"><Link href="/demo" className="mb-5 inline-flex min-h-10 items-center gap-2 text-[13px] font-medium text-[#6E6E73]"><ArrowLeft size={16} />Ana Sayfa</Link><div className="mb-7"><p className="text-[12px] font-semibold text-[#0071E3]">Maliyet ✓ &nbsp; Fiyat ✓ &nbsp; Teklif</p><h1 className="mt-2 text-[34px] font-semibold tracking-[-0.055em] sm:text-[42px]">Teklifini hazırla.</h1><p className="mt-2 text-[15px] text-[#6E6E73]">Örnek teklifin kapsamını ve müşterinin göreceği belgeyi incele.</p></div><div className="grid gap-6 xl:grid-cols-[minmax(0,1fr)_minmax(390px,0.95fr)] xl:items-start"><div className="space-y-5"><Card className="p-5 sm:p-7"><p className="text-[12px] font-semibold uppercase tracking-[0.12em] text-[#0071E3]">01 / Temel bilgiler</p><h2 className="mt-2 text-[20px] font-semibold">Bu teklif kimin için?</h2><p className="mt-5 text-[13px] text-[#6E6E73]">Müşteri</p><p className="mt-1 text-[15px] font-semibold">Ayşe Demir</p><p className="mt-5 text-[13px] text-[#6E6E73]">İş</p><p className="mt-1 text-[15px] font-semibold">Salon ve koridor boya işi</p></Card><Card className="p-5 sm:p-7"><p className="text-[12px] font-semibold uppercase tracking-[0.12em] text-[#0071E3]">02 / Kapsam</p><h2 className="mt-2 text-[20px] font-semibold">Teklife dahil</h2><div className="mt-5 space-y-3">{demoQuotePreview.items.map((item) => <div key={item.name} className="rounded-[14px] border border-[#e5e5e9] bg-[#fcfcfd] p-4"><p className="text-[14px] font-semibold">{item.name}</p><p className="mt-1 text-[13px] text-[#6E6E73]">{item.description}</p></div>)}</div></Card><Card className="p-5 sm:p-7"><p className="text-[12px] font-semibold uppercase tracking-[0.12em] text-[#0071E3]">03 / Fiyat</p><h2 className="mt-2 text-[20px] font-semibold">Satış fiyatı</h2><p className="mt-5 text-[30px] font-semibold">42.500 ₺</p><p className="mt-2 text-[13px] text-[#6E6E73]">Bu örnekte düzenleme ve kaydetme kapalıdır.</p></Card></div><aside><p className="mb-3 text-[14px] font-semibold">Teklif Önizleme</p><QuotePreview quote={demoQuotePreview} /></aside></div></div>;
}
