import Link from "next/link";
import { notFound } from "next/navigation";
import { guides, guideChecks, contentUpdatedAt } from "@/lib/marketing/content";
import { breadcrumbs, JsonLd, siteMetadata, siteOrigin } from "@/lib/marketing/seo";
import { ContentCta } from "@/components/marketing/shell";
type Props={params:Promise<{slug:string}>};
export function generateStaticParams(){return guides.map(g=>({slug:g.slug}));}
export async function generateMetadata({params}:Props){const {slug}=await params;const g=guides.find(x=>x.slug===slug);return g?siteMetadata(g.title,g.answer,`/rehber/${g.slug}`):{};}
export default async function Page({params}:Props){const {slug}=await params;const g=guides.find(x=>x.slug===slug);if(!g)notFound();const url=`${siteOrigin}/rehber/${g.slug}`;return <article className="mx-auto max-w-3xl px-5 py-16"><JsonLd data={[breadcrumbs([{name:"Ana Sayfa",path:"/"},{name:"Rehber",path:"/rehber"},{name:g.title,path:`/rehber/${g.slug}`}]),{"@context":"https://schema.org","@type":"Article",headline:g.title,description:g.answer,dateModified:contentUpdatedAt,datePublished:contentUpdatedAt,author:{"@type":"Organization",name:"KaçaYapayım"},publisher:{"@type":"Organization",name:"KaçaYapayım"},mainEntityOfPage:url}]}/><nav aria-label="İçerik yolu" className="mb-10 text-sm text-[#6e6e73]"><Link href="/">Ana Sayfa</Link> / <Link href="/rehber">Rehber</Link></nav><p className="marketing-eyebrow">Fiyatlandırma rehberi</p><h1 className="mt-4 text-[clamp(2.3rem,5vw,3.7rem)] font-semibold leading-tight tracking-[-.05em]">{g.title}</h1><p className="mt-5 text-sm text-[#77777d]">KaçaYapayım Editör Ekibi · Son güncelleme: <time dateTime={contentUpdatedAt}>30 Eylül 2026</time></p><p className="mt-10 rounded-2xl border-l-4 border-[#0071e3] bg-white p-6 text-lg leading-8">{g.answer}</p><section className="mt-12"><h2 className="text-2xl font-semibold">Formül</h2><p className="mt-4 rounded-2xl bg-[#eaf4ff] p-6 font-medium leading-8">{g.formula}</p></section><section className="mt-12"><h2 className="text-2xl font-semibold">Örnek hesap</h2><p className="mt-4 text-lg leading-8 text-[#55555d]">{g.example}</p></section><section className="mt-12"><h2 className="text-2xl font-semibold">Uygulamada neye dikkat etmeli?</h2><p className="mt-4 text-lg leading-8 text-[#55555d]">{g.detail}</p></section><section className="mt-12"><h2 className="text-2xl font-semibold">{guideChecks[g.slug].heading}</h2><ul className="mt-5 space-y-3">{guideChecks[g.slug].items.map(item=><li key={item} className="rounded-2xl bg-white p-5 leading-7 text-[#55555d]">{item}</li>)}</ul><p className="mt-5 text-sm leading-7 text-[#6e6e73]">{guideChecks[g.slug].caution}</p></section><section className="mt-12"><h2 className="text-2xl font-semibold">İlgili içerikler</h2><div className="mt-5 flex flex-wrap gap-3"><Link className="marketing-secondary" href={g.related}>Hesaplama aracını aç</Link><Link className="marketing-secondary" href="/metodoloji">Metodolojiyi oku</Link><Link className="marketing-secondary" href="/rehber">Tüm yazılar</Link></div></section><ContentCta/></article>}
