import Link from "next/link";
import { ArrowRight, Plus } from "lucide-react";
import { DashboardPeriodFilter } from "@/components/dashboard/period-filter";
import { EmptyState } from "@/components/content";
import { ButtonLink, Card, MetricCard, SectionCard } from "@/components/ui";
import { formatMoney, formatPercent } from "@/lib/costs/format";
import { formatQuoteDate, todayInIstanbul } from "@/lib/quotes/defaults";
import { quoteStatusCopy } from "@/lib/quotes/format";
import { rejectionReasonLabel } from "@/lib/quotes/decision";
import { deriveDashboardMetrics, type DashboardOverview } from "@/lib/dashboard/metrics";
import type { DashboardRange } from "@/lib/dashboard/range";
import { jobStatusLabel } from "@/lib/jobs/lifecycle";
import type { JobStatus, QuoteStatus } from "@/types/database";

const shortDate = (timestamp: string) => new Intl.DateTimeFormat("tr-TR", { day: "numeric", month: "short", timeZone: "Europe/Istanbul" }).format(new Date(timestamp));
const rate = (value: number) => `%${new Intl.NumberFormat("tr-TR", { maximumFractionDigits: 1 }).format(value)}`;
const linkClass = "inline-flex min-h-10 items-center gap-1 text-[13px] font-semibold text-[#0071E3] hover:underline focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-[#0071E3]";
const quoteLabel = (quote: DashboardOverview["recentQuotes"][number]) => {
  const status = ["ready", "sent", "viewed"].includes(quote.status) && quote.validUntil < todayInIstanbul() ? "expired" : quote.status;
  return quoteStatusCopy[status as QuoteStatus] || status;
};
const activitySentence = (type: string, customer: string) => {
  const copy: Record<string, string> = {
    quote_created: `${customer} için teklif oluşturuldu.`, quote_sent: `${customer} için teklif paylaşıldı.`,
    quote_viewed: `${customer} teklifinizi görüntüledi.`, quote_accepted: `${customer} teklifi kabul etti.`,
    quote_rejected: `${customer} teklifi reddetti.`, job_started: `${customer} için iş başladı.`,
    job_completed: `${customer} için iş tamamlandı.`,
  };
  return copy[type] || `${customer} ile ilgili işlem yapıldı.`;
};

export function DashboardContent({ data, range, businessName, firstName, advancedReports = true }: { data: DashboardOverview; range: DashboardRange; businessName: string; firstName: string; advancedReports?: boolean }) {
  const derived = deriveDashboardMetrics(data);
  const noData = !data.hasAnyQuote;
  const metrics = [
    { label: "Teklif Verilen", value: formatMoney(data.volume.amount), detail: `${data.volume.count} teklif`, tone: "blue" as const },
    { label: "Kabul Edilen", value: formatMoney(data.decisions.acceptedAmount), detail: `${data.decisions.acceptedCount} iş`, tone: "green" as const },
    { label: "Gerçek Kâr", value: advancedReports && data.completed.count ? formatMoney(data.completed.actualProfit) : "—", detail: advancedReports ? (data.completed.count ? `${data.completed.count} tamamlanan iş` : "Henüz tamamlanan iş yok") : "Usta paketinde", tone: "neutral" as const },
    { label: "Devam Eden", value: `${data.active.count} iş`, detail: `${formatMoney(data.active.volume)} iş hacmi`, tone: "amber" as const },
  ];
  const variance = derived.profitVariance;
  const heading = <section className="mb-8 flex flex-col gap-5 lg:flex-row lg:items-end lg:justify-between"><div><p className="text-[13px] font-medium text-[#77777e]">{businessName} / Genel Bakış</p><h1 className="mt-2 text-[34px] font-semibold leading-tight tracking-[-0.055em] sm:text-[44px]">İşin nasıl gidiyor, {firstName}?</h1><p className="mt-2 text-[14px] text-[#6E6E73]">{range.label} · {formatQuoteDate(range.startDate)} – {formatQuoteDate(range.endDate)}</p></div><div className="flex flex-col items-start gap-3"><DashboardPeriodFilter range={range} /><ButtonLink href="/new-quote" className="min-h-11 w-full sm:w-auto"><Plus size={17} />Yeni Teklif</ButtonLink></div></section>;
  if (noData) return <>{heading}<EmptyState title="İlk teklifini oluşturarak başla." description="Maliyetini hesapla, doğru fiyatı belirle ve müşterine gönder." action={{ label: "İlk Teklifimi Oluştur", href: "/new-quote" }} /></>;
  if (!advancedReports) return <>{heading}<section aria-label="Dönem özeti" className="grid grid-cols-2 gap-3 lg:grid-cols-4">{metrics.map((metric) => <MetricCard key={metric.label} {...metric} />)}</section><Card className="mt-6 p-6 sm:p-8"><h2 className="text-[20px] font-semibold">İşini daha ayrıntılı gör.</h2><p className="mt-2 text-[14px] text-[#6E6E73]">Gerçek kâr karşılaştırması ve teklif performansı Usta paketinde.</p><Link href="/billing" className="mt-5 inline-flex min-h-11 items-center rounded-[12px] bg-[#0071E3] px-5 text-[13px] font-semibold text-white">Paketleri Gör</Link></Card></>;
  return <>{heading}
    <p className="mb-5 text-[14px] text-[#515159]">{data.decisions.acceptedCount > 0 ? `${range.label} ${data.decisions.acceptedCount} teklif kabul edildi.` : data.pending.count > 0 ? `${data.pending.count} teklif yanıt bekliyor.` : `${range.label} ${data.volume.count} teklif hazırlandı.`}</p>
    <section aria-label="Dönem özeti" className="grid grid-cols-2 gap-3 lg:grid-cols-4">{metrics.map((metric) => <MetricCard key={metric.label} {...metric} />)}</section>
    <p className="mt-2 text-xs text-[#8a8a91]">Teklif tutarı taslak ve iptal edilenleri içermez. Kabul edilen tutar tahsilat anlamına gelmez.</p>
    <div className="mt-6 grid gap-5 xl:grid-cols-2"><SectionCard title="Kârlılık"><div className="p-5 sm:p-6">{data.completed.count ? <><div className="grid grid-cols-2 gap-5"><div><p className="text-xs text-[#6E6E73]">Tahmini kâr</p><p className="mt-2 text-xl font-semibold tabular-nums">{formatMoney(data.completed.estimatedProfit)}</p></div><div><p className="text-xs text-[#6E6E73]">Gerçek kâr</p><p className="mt-2 text-xl font-semibold tabular-nums">{formatMoney(data.completed.actualProfit)}</p></div></div><p className={`mt-5 border-t border-[#ececf0] pt-4 text-sm ${variance !== null && variance < 0 ? "text-[#9a6a29]" : "text-[#247344]"}`}>{variance === null || variance === 0 ? "Tamamlanan işlerde kâr tahmininle aynı." : variance < 0 ? `Tamamlanan işlerde tahmininden ${formatMoney(-variance)} daha az kâr ettin.` : `Tamamlanan işlerde tahmininden ${formatMoney(variance)} daha fazla kâr ettin.`}</p></> : <p className="text-sm text-[#6E6E73]">Henüz tamamlanan iş yok. Gerçek kâr karşılaştırması iş tamamlandığında görünür.</p>}<div className="mt-5 rounded-[13px] bg-[#f5f5f7] px-4 py-3"><p className="text-xs text-[#6E6E73]">Aktif işlerden beklenen kâr</p><p className="mt-1 font-semibold">{formatMoney(data.active.expectedProfit)}</p></div></div></SectionCard>
      <SectionCard title="Teklif Performansı"><div className="p-5 sm:p-6"><p className="text-xs text-[#6E6E73]">Teklif kabul oranı</p><p className="mt-2 text-[34px] font-semibold tracking-[-0.05em]">{derived.acceptanceRate === null ? "—" : rate(derived.acceptanceRate)}</p><p className="mt-1 text-sm text-[#6E6E73]">{derived.acceptanceRate === null ? "Henüz yeterli veri yok." : `${data.decisions.acceptedCount + data.decisions.rejectedCount} sonuçlanan tekliften ${data.decisions.acceptedCount} kabul edildi.`}</p><div className="mt-5 grid grid-cols-2 gap-3 border-t border-[#ececf0] pt-4 text-sm"><div><p className="text-[#6E6E73]">Bekleyen teklifler</p><p className="mt-1 font-semibold">{data.pending.count} · {formatMoney(data.pending.amount)}</p></div><div><p className="text-[#6E6E73]">Kaybedilen teklifler</p><p className="mt-1 font-semibold">{data.lost.count} · {formatMoney(data.lost.amount)}</p></div></div><p className="mt-5 text-xs font-medium text-[#6E6E73]">Dönemdeki hareketler</p><div className="mt-2 grid grid-cols-4 gap-2 text-center text-xs">{[["Gönderildi",data.funnel.sent],["Görüldü",data.funnel.viewed],["Kabul",data.funnel.accepted],["Red",data.funnel.rejected]].map(([label,count]) => <div key={label} className="rounded-xl bg-[#f5f5f7] px-2 py-3"><p className="font-semibold">{count}</p><p className="mt-1 text-[#6E6E73]">{label}</p></div>)}</div></div></SectionCard></div>
    <SectionCard title="Devam Eden İşler" action={<Link href="/jobs" className={linkClass}>Tümünü Gör <ArrowRight size={15} /></Link>} className="mt-5">{data.activeJobs.length ? <div className="divide-y divide-[#ececf0]">{data.activeJobs.map((job) => <Link key={job.id} href={`/jobs/${job.id}`} className="flex items-center justify-between gap-4 px-5 py-4 hover:bg-[#fafafa] sm:px-6"><div className="min-w-0"><p className="truncate text-sm font-semibold">{job.title}</p><p className="mt-1 text-xs text-[#6E6E73]">{job.customer} · {jobStatusLabel[job.status as JobStatus]}{job.startedAt ? ` · Başladı ${shortDate(job.startedAt)}` : ""}</p></div><span className="shrink-0 text-sm font-semibold tabular-nums">{formatMoney(job.amount)}</span></Link>)}</div> : <div className="px-5 py-7 text-sm text-[#6E6E73]">Şu anda bu dönemde kabul edilmiş devam eden işin yok. <Link href="/quotes" className="font-semibold text-[#0071E3]">Tekliflere Git</Link></div>}</SectionCard>
    <div className="mt-5 grid gap-5 xl:grid-cols-2"><SectionCard title="Son Teklifler" action={<Link href="/quotes" className={linkClass}>Tümünü Gör <ArrowRight size={15} /></Link>}>{data.recentQuotes.length ? <div className="divide-y divide-[#ececf0]">{data.recentQuotes.map((quote) => <Link key={quote.id} href={`/quotes/${quote.id}`} className="flex items-center justify-between gap-3 px-5 py-4 hover:bg-[#fafafa] sm:px-6"><div className="min-w-0"><p className="truncate text-sm font-semibold">{quote.customer}</p><p className="mt-1 truncate text-xs text-[#6E6E73]">{quote.title} · {quote.number}</p><p className="mt-1 text-xs text-[#8a8a91]">{shortDate(quote.date)}</p></div><div className="shrink-0 text-right"><p className="text-sm font-semibold tabular-nums">{formatMoney(quote.amount)}</p><p className="mt-1 text-xs text-[#6E6E73]">{quoteLabel(quote)}</p></div></Link>)}</div> : <p className="px-5 py-8 text-sm text-[#6E6E73]">Bu dönemde teklif yok.</p>}</SectionCard>
      <SectionCard title="En Kârlı İşler" action={<Link href="/jobs?status=completed" className={linkClass}>İşleri Gör <ArrowRight size={15} /></Link>}>{data.topJobs.length ? <div className="divide-y divide-[#ececf0]">{data.topJobs.map((job) => <Link key={job.id} href={`/jobs/${job.id}`} className="flex items-center justify-between gap-3 px-5 py-4 hover:bg-[#fafafa] sm:px-6"><div className="min-w-0"><p className="truncate text-sm font-semibold">{job.title}</p><p className="mt-1 text-xs text-[#6E6E73]">{job.customer} · Teklif {formatMoney(job.salePrice)}</p></div><div className="shrink-0 text-right"><p className="text-sm font-semibold tabular-nums">{formatMoney(job.profit)}</p><p className="mt-1 text-xs text-[#6E6E73]">{formatPercent(job.margin)} marj</p></div></Link>)}</div> : <p className="px-5 py-8 text-sm text-[#6E6E73]">Bu dönemde tamamlanan iş yok.</p>}</SectionCard></div>
    <div className="mt-5 grid gap-5 xl:grid-cols-2"><SectionCard title="Kaybedilen Teklifler"><div className="p-5 sm:p-6"><p className="text-2xl font-semibold">{data.lost.count} teklif</p><p className="mt-1 text-sm text-[#6E6E73]">{formatMoney(data.lost.amount)} potansiyel tutar</p>{data.reasons.length > 0 && <div className="mt-5 border-t border-[#ececf0] pt-4"><p className="mb-3 text-xs font-medium text-[#6E6E73]">Red nedenleri</p>{data.reasons.map((reason) => <div key={reason.reason} className="mt-2 flex justify-between text-sm"><span>{rejectionReasonLabel(reason.reason)}</span><span className="font-semibold">{reason.count}</span></div>)}</div>}</div></SectionCard>
      <SectionCard title="Son Hareketler">{data.activity.length ? <div className="divide-y divide-[#ececf0]">{data.activity.map((event, index) => <Link key={`${event.type}-${event.id}-${index}`} href={`${event.type.startsWith("job_") ? "/jobs" : "/quotes"}/${event.id}`} className="block px-5 py-3 hover:bg-[#fafafa] sm:px-6"><p className="text-sm">{activitySentence(event.type, event.customer)}</p><p className="mt-1 truncate text-xs text-[#8a8a91]">{event.title} · {shortDate(event.at)}</p></Link>)}</div> : <p className="px-5 py-8 text-sm text-[#6E6E73]">Bu dönemde hareket yok.</p>}</SectionCard></div>
    <Card className="mt-5 p-5 sm:p-6"><h2 className="text-sm font-semibold">Güncel İş Durumları</h2><p className="mt-1 text-xs text-[#6E6E73]">Bu satır seçilen dönemden bağımsız olarak şu anki işlerini gösterir.</p><div className="mt-4 grid grid-cols-2 gap-3 text-sm sm:grid-cols-5">{[["Kabul Edildi",data.statuses.accepted],["Planlandı",data.statuses.scheduled],["Devam Ediyor",data.statuses.inProgress],["Tamamlandı",data.statuses.completed],["İptal",data.statuses.cancelled]].map(([label,count]) => <div key={label} className="rounded-xl bg-[#f5f5f7] p-3"><p className="text-xs text-[#6E6E73]">{label}</p><p className="mt-2 text-xl font-semibold">{count}</p></div>)}</div></Card>
  </>;
}
