import Link from "next/link";
import { ChevronLeft, ChevronRight, Plus } from "lucide-react";
import { ButtonLink, Card } from "@/components/ui";
import { CustomerSearch } from "@/components/customers/customer-search";
import { getCustomers } from "@/lib/customers/service";
import { customerInitials, customerLocation, formatCustomerDate, formatTurkishPhone } from "@/lib/customers/format";

export const metadata = { title: "Müşteriler" };
type SearchParams = { q?: string; view?: string; page?: string };

export default async function CustomersPage({ searchParams }: { searchParams: Promise<SearchParams> }) {
  const params = await searchParams;
  const query = typeof params.q === "string" ? params.q.slice(0, 80) : "";
  const archived = params.view === "archive";
  const page = Math.max(1, Number.parseInt(params.page || "1", 10) || 1);
  const result = await getCustomers({ query, archived, page });
  const hrefFor = (nextPage: number) => `/customers?${new URLSearchParams({ ...(query ? { q: query } : {}), ...(archived ? { view: "archive" } : {}), page: String(nextPage) })}`;
  const tabHref = (archive: boolean) => `/customers${archive ? `?view=archive${query ? `&q=${encodeURIComponent(query)}` : ""}` : query ? `?q=${encodeURIComponent(query)}` : ""}`;
  return <div className="mx-auto max-w-[1100px]"><header className="mb-7 flex flex-col gap-5 sm:flex-row sm:items-end sm:justify-between"><div><h1 className="text-[34px] font-semibold leading-[1.08] tracking-[-0.055em] sm:text-[42px]">Müşteriler</h1><p className="mt-3 text-[15px] leading-6 text-[#6E6E73]">Müşterilerini ve iletişim bilgilerini tek yerden yönet.</p></div><ButtonLink href="/customers/new" className="min-h-12 w-full shrink-0 sm:w-auto"><Plus size={18} />Yeni Müşteri</ButtonLink></header>
    <div className="mb-5 flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div className="w-full sm:max-w-[380px]"><CustomerSearch initialQuery={query} archived={archived} /></div><p className="text-[13px] font-medium text-[#6E6E73]">{result.count} {archived ? "arşivlenmiş" : "aktif"} müşteri</p></div>
    <nav aria-label="Müşteri görünümü" className="mb-5 inline-flex rounded-[13px] bg-[#e9e9ed] p-1 text-[14px] font-medium"><Link href={tabHref(false)} aria-current={!archived ? "page" : undefined} className={`min-w-24 rounded-[10px] px-4 py-2.5 text-center ${!archived ? "bg-white text-[#1D1D1F] shadow-sm" : "text-[#6E6E73]"}`}>Aktif</Link><Link href={tabHref(true)} aria-current={archived ? "page" : undefined} className={`min-w-24 rounded-[10px] px-4 py-2.5 text-center ${archived ? "bg-white text-[#1D1D1F] shadow-sm" : "text-[#6E6E73]"}`}>Arşiv</Link></nav>
    {!result.customers.length ? <Card className="flex min-h-[280px] flex-col items-center justify-center px-6 py-10 text-center"><h2 className="text-[20px] font-semibold tracking-tight">{query ? "Aramana uygun müşteri bulunamadı." : archived ? "Arşivde müşteri yok." : "Müşterilerini eklemeye başla."}</h2><p className="mt-2 max-w-md text-[14px] leading-6 text-[#6E6E73]">{query ? "Yeni müşteri eklemek ister misin?" : archived ? "Arşivlediğin müşteriler burada görünür." : "Tekliflerini müşterilere bağlayarak geçmişini ve işlerini kolayca takip edebilirsin."}</p>{!archived && <ButtonLink href="/customers/new" className="mt-6">{query ? "Yeni Müşteri" : "İlk Müşterini Ekle"}</ButtonLink>}</Card> : <Card className="overflow-hidden"><div className="hidden grid-cols-[minmax(220px,1.5fr)_minmax(140px,1fr)_minmax(140px,1fr)_135px_18px] gap-4 border-b border-[#ececf0] px-6 py-3 text-[12px] font-semibold text-[#6E6E73] xl:grid"><span>Müşteri</span><span>Telefon</span><span>Şehir</span><span>Eklenme tarihi</span><span /></div>{result.customers.map((customer) => <Link key={customer.id} href={`/customers/${customer.id}`} className="flex min-h-[88px] items-center gap-3 border-b border-[#ececf0] px-5 py-4 transition-colors hover:bg-[#fafafb] focus-visible:outline-2 focus-visible:outline-offset-[-2px] focus-visible:outline-[#0071E3] last:border-0 xl:grid xl:grid-cols-[minmax(220px,1.5fr)_minmax(140px,1fr)_minmax(140px,1fr)_135px_18px] xl:gap-4 xl:px-6"><div className="flex min-w-0 items-center gap-3"><span aria-hidden="true" className="flex size-11 shrink-0 items-center justify-center rounded-full bg-[#e9f2fb] text-[13px] font-semibold text-[#1766ad]">{customerInitials(customer.name)}</span><div className="min-w-0"><p className="truncate text-[15px] font-semibold">{customer.name}</p>{customer.company_name && <p className="mt-0.5 truncate text-[12px] text-[#6E6E73]">{customer.company_name}</p>}<p className="mt-1 text-[13px] text-[#6E6E73] xl:hidden">{formatTurkishPhone(customer.phone)}</p>{customerLocation(customer.district, customer.city) && <p className="mt-0.5 truncate text-[13px] text-[#6E6E73] xl:hidden">{customerLocation(customer.district, customer.city)}</p>}</div></div><span className="hidden text-[14px] text-[#515159] xl:block">{formatTurkishPhone(customer.phone)}</span><span className="hidden truncate text-[14px] text-[#515159] xl:block">{customerLocation(customer.district, customer.city) || "—"}</span><span className="hidden text-[13px] text-[#6E6E73] xl:block">{formatCustomerDate(customer.created_at)}</span><ChevronRight size={18} className="ml-auto shrink-0 text-[#a0a0a6] xl:ml-0" /></Link>)}</Card>}
    {result.count > result.pageSize && <div className="mt-5 flex items-center justify-between gap-3 text-[13px] text-[#6E6E73]"><span>Sayfa {result.page} / {Math.ceil(result.count / result.pageSize)}</span><div className="flex gap-2">{result.page > 1 && <Link href={hrefFor(result.page - 1)} className="inline-flex min-h-11 items-center gap-1 rounded-xl border border-[#D2D2D7] bg-white px-3 font-medium text-[#1D1D1F]"><ChevronLeft size={16} />Önceki</Link>}{result.page * result.pageSize < result.count && <Link href={hrefFor(result.page + 1)} className="inline-flex min-h-11 items-center gap-1 rounded-xl border border-[#D2D2D7] bg-white px-3 font-medium text-[#1D1D1F]">Sonraki<ChevronRight size={16} /></Link>}</div></div>}
  </div>;
}
