import Link from "next/link";
import { notFound } from "next/navigation";
import { ArrowLeft, MessageCircle, Pencil, Phone, Plus } from "lucide-react";
import { CustomerStatusActions } from "@/components/customers/customer-status-actions";
import { ButtonLink, Card } from "@/components/ui";
import { customerSourceLabel } from "@/lib/customers/catalog";
import { getCustomerById } from "@/lib/customers/service";
import { customerInitials, customerLocation, formatCustomerDate, formatTurkishPhone } from "@/lib/customers/format";
import { formatMoney } from "@/lib/costs/format";
import { getJobsForCustomer } from "@/lib/jobs/service";
import { getQuotesForCustomer } from "@/lib/quotes/service";
import { QuoteStatusBadge } from "@/lib/quotes/format";
import { dateInIstanbul, formatQuoteDate } from "@/lib/quotes/defaults";

export const metadata = { title: "Müşteri" };
type Props = { params: Promise<{ id: string }>; searchParams: Promise<{ updated?: string; created?: string }> };

export default async function CustomerDetailPage({ params, searchParams }: Props) {
  const { id } = await params;
  const flags = await searchParams;
  const customer = await getCustomerById(id);
  if (!customer) notFound();
  const [recentJobs, recentQuotes] = await Promise.all([getJobsForCustomer(id), getQuotesForCustomer(id)]);
  const location = customerLocation(customer.district, customer.city);
  const initialNotice = flags.updated === "1" ? "Müşteri bilgileri güncellendi." : flags.created === "1" ? "Müşteri kaydedildi." : undefined;
  return <div className="mx-auto max-w-[960px]"><Link href="/customers" className="mb-5 inline-flex min-h-11 items-center gap-2 text-[14px] font-medium text-[#6E6E73] hover:text-[#1D1D1F]"><ArrowLeft size={17} />Müşteriler</Link>
    <Card className="p-5 sm:p-7"><div className="flex flex-col gap-5 sm:flex-row sm:items-start sm:justify-between"><div className="flex items-start gap-4"><span aria-hidden="true" className="flex size-14 shrink-0 items-center justify-center rounded-full bg-[#e9f2fb] text-[18px] font-semibold text-[#1766ad] sm:size-16">{customerInitials(customer.name)}</span><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><h1 className="text-[27px] font-semibold leading-tight tracking-[-0.045em] sm:text-[34px]">{customer.name}</h1>{customer.is_archived && <span className="rounded-full bg-[#f1f1f3] px-2.5 py-1 text-[12px] font-medium text-[#6E6E73]">Arşivde</span>}</div>{customer.company_name && <p className="mt-1 text-[15px] text-[#515159]">{customer.company_name}</p>}{customer.phone && <p className="mt-2 text-[14px] text-[#6E6E73]">{formatTurkishPhone(customer.phone)}</p>}{location && <p className="mt-1 text-[14px] text-[#6E6E73]">{location}</p>}</div></div><div className="flex shrink-0 gap-2"><ButtonLink href={`/customers/${id}/edit`} variant="secondary" className="min-h-11 flex-1 sm:flex-none"><Pencil size={16} />Düzenle</ButtonLink><CustomerStatusActions id={id} archived={customer.is_archived} initialNotice={initialNotice} /></div></div>{customer.phone && <div className="mt-6 flex gap-2 border-t border-[#ececf0] pt-5"><a href={`tel:${customer.phone}`} className="inline-flex min-h-11 flex-1 items-center justify-center gap-2 rounded-[13px] bg-[#0071E3] px-4 text-[14px] font-semibold text-white sm:flex-none"><Phone size={17} />Ara</a><a href={`https://wa.me/${customer.phone.replace(/\D/g, "")}`} target="_blank" rel="noopener noreferrer" className="inline-flex min-h-11 flex-1 items-center justify-center gap-2 rounded-[13px] border border-[#D2D2D7] bg-white px-4 text-[14px] font-semibold sm:flex-none"><MessageCircle size={17} />WhatsApp</a></div>}</Card>
    <div className="mt-5 grid gap-5 sm:grid-cols-2"><Card className="p-5 sm:p-6"><h2 className="text-[18px] font-semibold">İletişim</h2><dl className="mt-5 space-y-4"><div><dt className="text-[12px] text-[#6E6E73]">Telefon</dt><dd className="mt-1 break-words text-[14px] font-medium">{customer.phone ? <a className="text-[#0071E3]" href={`tel:${customer.phone}`}>{formatTurkishPhone(customer.phone)}</a> : "Eklenmedi"}</dd></div><div><dt className="text-[12px] text-[#6E6E73]">E-posta</dt><dd className="mt-1 break-all text-[14px] font-medium">{customer.email ? <a className="text-[#0071E3]" href={`mailto:${customer.email}`}>{customer.email}</a> : "Eklenmedi"}</dd></div><div><dt className="text-[12px] text-[#6E6E73]">Firma</dt><dd className="mt-1 text-[14px] font-medium">{customer.company_name || "Eklenmedi"}</dd></div></dl></Card><Card className="p-5 sm:p-6"><h2 className="text-[18px] font-semibold">Adres</h2><p className="mt-5 text-[14px] font-medium">{location || "Şehir ve ilçe eklenmedi"}</p><p className="mt-2 whitespace-pre-wrap text-[14px] leading-6 text-[#6E6E73]">{customer.address || "Açık adres eklenmedi."}</p></Card></div>
    <Card className="mt-5 p-5 sm:p-6"><h2 className="text-[18px] font-semibold">Notlar</h2><p className="mt-4 whitespace-pre-wrap text-[14px] leading-6 text-[#515159]">{customer.notes || "Henüz not eklenmedi."}</p></Card>
    <div className="mt-5 grid gap-5 sm:grid-cols-2"><Card className="p-5 sm:p-6"><h2 className="text-[18px] font-semibold">Geçmiş</h2>{recentQuotes.length > 0 && <div className="mt-4"><p className="text-[12px] font-semibold uppercase tracking-wide text-[#62626a]">Teklifler</p><div className="mt-2 divide-y divide-[#ececf0]">{recentQuotes.map((quote) => <Link key={quote.id} href={`/quotes/${quote.id}`} className="flex min-h-16 items-center justify-between gap-3 py-2 text-[14px] hover:text-[#0071E3]"><span className="min-w-0"><span className="block font-semibold">{quote.quote_number}</span><span className="mt-0.5 block truncate text-[12px] text-[#6E6E73]">{quote.title} · {formatMoney(quote.sale_price)} · {formatQuoteDate(dateInIstanbul(quote.created_at))}</span></span><QuoteStatusBadge quote={quote} /></Link>)}</div></div>}{recentJobs.length > 0 && <div className="mt-4"><p className="text-[12px] font-semibold uppercase tracking-wide text-[#62626a]">İşler</p><div className="mt-2 divide-y divide-[#ececf0]">{recentJobs.map((job) => <Link key={job.id} href={`/jobs/${job.id}`} className="flex min-h-14 items-center justify-between gap-3 py-2 text-[14px] hover:text-[#0071E3]"><span className="min-w-0 truncate font-medium">{job.title}</span><span className="shrink-0 text-[13px] tabular-nums">{formatMoney(job.estimated_cost)}</span></Link>)}</div></div>}{!recentQuotes.length && !recentJobs.length && <p className="mt-4 text-[14px] leading-6 text-[#6E6E73]">Bu müşteri için henüz teklif veya iş yok.</p>}<ButtonLink href={`/new-quote?customer_id=${customer.id}`} className="mt-5 w-full sm:w-auto"><Plus size={17} />Yeni Teklif Oluştur</ButtonLink></Card><Card className="p-5 sm:p-6"><h2 className="text-[18px] font-semibold">Kayıt Bilgisi</h2><dl className="mt-4 space-y-3 text-[14px]"><div className="flex justify-between gap-4"><dt className="text-[#6E6E73]">Eklenme tarihi</dt><dd className="text-right font-medium">{formatCustomerDate(customer.created_at)}</dd></div><div className="flex justify-between gap-4"><dt className="text-[#6E6E73]">Müşteri kaynağı</dt><dd className="text-right font-medium">{customerSourceLabel(customer.source)}</dd></div></dl></Card></div>
  </div>;
}
