"use client";
import Link from "next/link";
import { useEffect, useState } from "react";
import { saveWorkEntry, updateWorkEntry } from "@/app/actions/work";
import { entryKinds, type EntryKind, type WorkEntry } from "@/lib/work/types";
import { formatMoney } from "@/lib/costs/format";
import { Dialog } from "@/components/ui/dialog";
import { useDraft } from "@/components/draft-provider";
import { FileUploader } from "@/components/work/file-uploader";
import { VoiceNote } from "@/components/work/voice-note";
const control="mt-2 min-h-12 w-full rounded-xl border border-[#d8d8de] bg-white p-3 text-base";
export function WorkBoard({ initialEntries, jobId, quoteId }: { initialEntries: WorkEntry[]; jobId?: string; quoteId?: string }) {
 const [entries,setEntries]=useState(initialEntries); const [filter,setFilter]=useState('all');const [showDone,setShowDone]=useState(false);
 const [calendarDay,setCalendarDay]=useState('');
 useEffect(()=>setEntries(initialEntries),[initialEntries]);
 const [adding,setAdding]=useState(false);const [kind,setKind]=useState<EntryKind>(quoteId?'followup':'note');
 const [title,setTitle]=useState('');const [note,setNote]=useState('');const [amount,setAmount]=useState('');const [date,setDate]=useState('');const [busy,setBusy]=useState(false);const [error,setError]=useState('');
 const draft=useDraft('work:'+(quoteId??jobId??'all'),{kind,title,note,amount,date},s=>{if(!Object.hasOwn(entryKinds,s.kind)||typeof s.title!=='string')return;setKind(s.kind);setTitle(s.title);setNote(s.note);setAmount(s.amount);setDate(s.date);});
 async function save(){if(busy)return;setBusy(true);setError('');try{const result=await saveWorkEntry({jobId,quoteId,kind,title,note,amount:amount===''?null:Number(amount),scheduledAt:date?new Date(date).toISOString():null});if(!result.ok||!result.entry){setError(result.error||'Kayıt eklenemedi.');return;}setEntries(old=>[result.entry!,...old]);draft.clear();setTitle('');setNote('');setAmount('');setDate('');setAdding(false);}catch{setError('Bağlantı kurulamadı. Alanların korunuyor.');}finally{setBusy(false);}}
 async function change(id:string,status:WorkEntry['status']){setBusy(true);setError('');try{const r=await updateWorkEntry(id,status);if(!r.ok){setError('Durum kaydedilemedi.');return;}setEntries(a=>a.map(e=>e.id===id?{...e,status}:e));}catch{setError('Bağlantı kurulamadı.');}finally{setBusy(false);}}
 const visible=entries.filter(e=>(filter==='all'||e.kind===filter)&&(showDone||e.status==='open')&&(!calendarDay||e.scheduled_at&&new Date(e.scheduled_at).toLocaleDateString('sv-SE',{timeZone:'Europe/Istanbul'})===calendarDay)).sort((a,b)=>(a.scheduled_at??'9999').localeCompare(b.scheduled_at??'9999'));
 const nearbyVisits=kind==='visit'&&date?entries.filter(e=>e.kind==='visit'&&e.status==='open'&&e.scheduled_at&&Math.abs(Date.parse(e.scheduled_at)-Date.parse(date))<3600000):[];
 return <section className="mt-7 rounded-[20px] border border-[#e5e5e9] bg-white p-5 sm:p-6"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-xl font-semibold">İş takibi ve saha kayıtları</h2><p className="mt-1 text-sm text-[#6E6E73]">Hatırlatmalar, keşifler, notlar ve ek işler.</p></div><button onClick={()=>{draft.resume();setAdding(true);}} className="min-h-11 rounded-xl bg-[#0071E3] px-4 text-sm font-semibold text-white">Kayıt Ekle</button></div>
 <div className="mt-5 flex flex-wrap gap-4"><label className="text-sm">Kayıt türü<select aria-label="Kayıt türü" value={filter} onChange={e=>setFilter(e.target.value)} className="ml-2 min-h-11 rounded-xl border border-[#e5e5e9] px-3"><option value="all">Tümü</option>{Object.entries(entryKinds).map(([k,label])=><option key={k} value={k}>{label}</option>)}</select></label><label className="flex min-h-11 items-center gap-2 text-sm"><input type="checkbox" checked={showDone} onChange={e=>setShowDone(e.target.checked)}/>Tamamlananları göster</label><label className="text-sm">Takvim günü<input type="date" value={calendarDay} onChange={e=>setCalendarDay(e.target.value)} className="ml-2 min-h-11 rounded-xl border border-[#e5e5e9] px-3"/></label>{calendarDay&&<button type="button" className="min-h-11 text-sm text-[#0071E3]" onClick={()=>setCalendarDay("")}>Tüm Günler</button>}</div>
 {error&&<p role="alert" className="mt-3 text-sm text-red-700">{error}</p>}
 <div className="mt-5 space-y-3">{visible.length?visible.map(e=><article key={e.id} className="rounded-xl border border-[#e5e5e9] p-4"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-xs text-[#6E6E73]">{entryKinds[e.kind]} · {e.status==='open'?'Bekliyor':e.status==='approved'?'Onaylandı':e.status==='declined'?'Reddedildi':'Tamamlandı'}</p><h3 className="mt-1 font-semibold">{e.title}</h3>{e.scheduled_at&&<p className={`mt-1 text-sm ${Date.parse(e.scheduled_at)<Date.now()&&e.status==='open'?'text-amber-800':'text-[#6E6E73]'}`}>{new Date(e.scheduled_at).toLocaleString('tr-TR',{timeZone:'Europe/Istanbul',dateStyle:'medium',timeStyle:'short'})}</p>}{e.amount!==null&&<p className="mt-1 font-semibold">{formatMoney(e.amount)}</p>}</div><button disabled={busy} onClick={()=>change(e.id,e.status==='open'?'done':'open')} className="min-h-11 rounded-xl border border-[#e5e5e9] px-3 text-sm">{e.status==='open'?'Tamamlandı İşaretle':'Yeniden Aç'}</button></div>{e.note&&<p className="mt-3 whitespace-pre-wrap text-sm text-[#55555d]">{e.note}</p>}<div className="mt-3 flex flex-wrap gap-3 text-sm">{!jobId&&e.job_id&&<Link className="text-[#0071E3]" href={`/jobs/${e.job_id}`}>İşi Aç</Link>}{!quoteId&&e.quote_id&&<Link className="text-[#0071E3]" href={`/quotes/${e.quote_id}`}>Teklifi Aç</Link>}{e.kind==='attachment'&&<a className="text-[#0071E3]" href={`/api/work/files/${e.id}`} target="_blank" rel="noopener noreferrer">Dosyayı Aç</a>}{e.kind==='extra_work'&&e.status==='open'&&<><button disabled={busy} onClick={()=>change(e.id,'approved')} className="min-h-11 text-[#0071E3]">Müşteri Onayladı</button><button disabled={busy} onClick={()=>change(e.id,'declined')} className="min-h-11 text-red-700">Müşteri Reddetti</button></>}</div></article>):<p className="rounded-xl bg-[#f5f5f7] p-4 text-sm text-[#6E6E73]">Bu filtrede kayıt yok.</p>}</div>
 {jobId&&<FileUploader jobId={jobId} onUploaded={e=>setEntries(a=>[e,...a])}/>}
 <p className="mt-4 text-xs leading-5 text-[#6E6E73]">İşe bağlı giderler gerçekleşen maliyete otomatik eklenir. Tamamlama ekranında aynı gideri tekrar girme. Ek iş onayı, müşterinin sana ilettiği kararı kaydetmek içindir.</p>
 {adding&&<Dialog title="Takip kaydı ekle" onClose={()=>setAdding(false)} busy={busy}><form onSubmit={e=>{e.preventDefault();void save();}} className="space-y-4"><label className="block text-sm font-medium">Tür<select value={kind} onChange={e=>setKind(e.target.value as EntryKind)} className={control}>{Object.entries(entryKinds).filter(([k])=>!['attachment','revision_request'].includes(k)).map(([k,label])=><option key={k} value={k}>{label}</option>)}</select></label><label className="block text-sm font-medium">Başlık<input required maxLength={160} value={title} onChange={e=>setTitle(e.target.value)} className={control}/></label><label className="block text-sm font-medium">Not<textarea value={note} onChange={e=>setNote(e.target.value)} maxLength={2000} rows={3} className={control}/></label><VoiceNote onText={text=>setNote(value=>(value?value+"\n":"")+text.slice(0,2000-value.length))}/>{['expense','extra_work'].includes(kind)&&<label className="block text-sm font-medium">Tutar (TL)<input type="number" min="0" step="0.01" value={amount} onChange={e=>setAmount(e.target.value)} className={control}/></label>}<label className="block text-sm font-medium">Tarih ve saat (isteğe bağlı)<input type="datetime-local" value={date} onChange={e=>setDate(e.target.value)} className={control}/></label>{nearbyVisits.length>0&&<p role="status" className="rounded-xl bg-amber-50 p-3 text-sm text-amber-900">Bu saatten bir saat önce veya sonra {nearbyVisits.length} keşif kaydı var. Randevuları kontrol et.</p>}{error&&<p role="alert" className="text-sm text-red-700">{error}</p>}<button disabled={busy} type="submit" className="min-h-12 w-full rounded-xl bg-[#0071E3] text-sm font-semibold text-white">{busy?'Kaydediliyor…':'Kaydet'}</button></form></Dialog>}
 </section>;
}
