"use client";
import {useState} from "react";
import {authorizeExport} from "@/app/actions/export";
import {Button,Input} from "@/components/ui";
const kinds={account:"Hesap arşivi (NDJSON)",customers:"Müşteriler",quotes:"Teklifler",costs:"Maliyetler",jobs:"İşler",expenses:"Gider ve saha kayıtları",files:"Dosya envanteri",payments:"Tahsilatlar"};
export function ExportPanel(){
 const [ready,setReady]=useState(false);const [busy,setBusy]=useState(false);const [message,setMessage]=useState("");
 return <section id="export" className="mt-6 rounded-2xl border bg-white p-6"><h2 className="text-lg font-semibold">Verilerini dışa aktar</h2><p className="mt-2 text-sm text-[#6e6e73]">Güncel parolanı doğrula. İndirme izni 10 dakika geçerlidir. Hesap arşivi profil, işletme, iş, teklif, izin ve maliyet ayrıntılarını içerir; dosya içeriklerini içermez. Bu arşivde son satırda complete kaydı yoksa indirme yarım kalmıştır. İndirme sırasında değişen kayıtlar farklı anları yansıtabilir. CSV dosyaları özel müşteri ve iş bilgileri içerebilir; güvenli bir yerde sakla. Dosya envanteri yüklenen belgeleri ve boyutlarını listeler; dosya içeriklerini iş ekranından ayrı indir.</p><form className="mt-4 space-y-3" onSubmit={async e=>{e.preventDefault();if(busy)return;setBusy(true);const form=new FormData(e.currentTarget);try{const r=await authorizeExport(form);setReady(r.ok);setMessage(r.ok?"İndirmeler 10 dakika için açıldı.":r.error||"Doğrulanamadı.");if(r.ok)window.setTimeout(()=>setReady(false),600000);}catch{setMessage("Bağlantı kurulamadı.");}finally{setBusy(false);}}}><Input id="export-password" name="password" label="Güncel parolan" type="password" autoComplete="current-password" required/><Button disabled={busy}>İndirmeyi aç</Button></form>{message&&<p role="status" className="mt-3 text-sm">{message}</p>}{ready&&<div className="mt-4 flex flex-wrap gap-3">{Object.entries(kinds).map(([key,label])=><a key={key} className="min-h-11 rounded-xl border px-4 py-3 text-sm text-[#0071e3]" href={`/api/export/${key}`}>{label}</a>)}</div>}</section>;
}
